export type RoadMapData = {
  title: string;
  subTitle: string;
  description: string;
};

export const roadmapData: RoadMapData[] = [
  {
    title: 'Mar',
    subTitle: '2022',
    description:
      'the start of cooperation with the Ministry of Digital Transformation of Ukraine.',
  },
  {
    title: 'Mar',
    subTitle: '2022',
    description:
      'Own Your Data Foundation co-founder Brittany Kaiser becomes the official ambassador of the project.',
  },
  {
    title: '30',
    subTitle: 'Mar, 2022',
    description: '1st Warline drop.',
  },
  {
    title: '17',
    subTitle: 'Apr, 2022',
    description:
      'closed auction (only for NFT project owners) of works created in collaboration with PROSPECT 100.',
  },
  {
    title: '22',
    subTitle: 'Apr, 2022',
    description:
      'the first virtual meeting of NFT project owners in Party Space.',
  },
  {
    title: '25',
    subTitle: 'Apr, 2022',
    description:
      'the world-famous digital artist Vesa becomes the official ambassador of the project.',
  },
  {
    title: '26',
    subTitle: 'Apr, 2022',
    description: 'the beginning of cooperation with Hacken.',
  },
  {
    title: '28',
    subTitle: 'Apr, 2022',
    description:
      'Ukraine DAO co-founder Alyona Shevchenko becomes the official ambassador of the project.',
  },
  {
    title: '29',
    subTitle: 'Apr, 2022',
    description:
      'release of the first NFT dedicated to Elon Musk from The Hall collection.',
  },
  {
    title: '1',
    subTitle: 'May, 2022',
    description: '2nd Warline drop.',
  },
  {
    title: '19',
    subTitle: 'May, 2022',
    description: '1st drop of Avatars for Ukraine.',
  },
  {
    title: '19',
    subTitle: 'May, 2022',
    description: 'virtual exhibition Avatars for Ukraine in Party Space.',
  },
  {
    title: '25',
    subTitle: 'May, 2022',
    description: 'NFT auction of the Eurovision Winners Cup.',
  },
  {
    title: '25',
    subTitle: 'May, 2022',
    description: 'the start of cooperation with Unchain Fund.',
  },
  {
    title: '29',
    subTitle: 'May, 2022',
    description: 'record bid per lot (500 ETH) on the project platform.',
  },
  {
    title: '30',
    subTitle: 'May, 2022',
    description:
      'the start of cooperation with the Ministry of Culture of Ukraine.',
  },
  {
    title: '31',
    subTitle: 'May, 2022',
    description:
      'the start of cooperation with Arsani ― the first auction house in Ukraine.',
  },
  {
    title: 'Jul',
    subTitle: '2022',
    description:
      'the project collected the first $1 million of assistance to the state.',
  },
  {
    title: '21',
    subTitle: 'Jul, 2022',
    description: '3rd Warline drop.',
  },
  {
    title: '4',
    subTitle: 'Aug, 2022',
    description:
      'exhibition of the 3rd Warline drop in the virtual space Party Space.',
  },
  {
    title: '4',
    subTitle: 'Aug, 2022',
    description:
      '4th Warline drop together with ZibraAI. The first drop for which art was generated by AI.',
  },
  {
    title: '14',
    subTitle: 'Aug, 2022',
    description:
      'UnchainFund co-founder Rev Miller becomes the official ambassador of the project.',
  },
  {
    title: '15',
    subTitle: 'Aug, 2022',
    description:
      'President of the Blockchain Association of Ukraine Michael Chobanian becomes the official ambassador of the project.',
  },
  {
    title: '23',
    subTitle: 'Aug, 2022',
    description:
      'a joint collection with Depositphotos and the Ministry of Culture. The first of the collections, the money from the sales of which will go to restore the cultural heritage of Ukraine.',
  },
  {
    title: '24',
    subTitle: 'Aug, 2022',
    description:
      'the project gallery opened during Art Week in one of the most popular meta-universes Decentraland.',
  },
  {
    title: '24',
    subTitle: 'Aug, 2022',
    description:
      'Minister of Culture of Ukraine Oleksandr Tkachenko and Everstake CEO Serhiy Vasylchuk become official ambassadors of the project.',
  },
  {
    title: '25',
    subTitle: 'Aug, 2022',
    description:
      '4th Warline drop is available for purchase with a regular card thanks to cooperation with Utorg.',
  },
  {
    title: '30',
    subTitle: 'Sep, 2022',
    description: 'release of the Meta Rooster collection.',
  },
  {
    title: '6',
    subTitle: 'Oct, 2022',
    description:
      'NFT from The Hall collection was accepted by Vitalik Buterin.',
  },
  {
    title: '7',
    subTitle: 'Oct, 2022',
    description: '5th Warline drop.',
  },
  {
    title: 'Oct',
    subTitle: '2022',
    description:
      'War line augmented reality exhibition in 20+ locations worldwide.',
  },
  {
    title: 'Oct',
    subTitle: '2022',
    description: '6th Warline drop.',
  },
  {
    title: 'Oct',
    subTitle: '2022',
    description: 'auction of Vesa and Zinaida artworks.',
  },
  {
    title: 'Nov',
    subTitle: '2022',
    description:
      'release of the collection together with Just Bricks Breakout.',
  },
  {
    title: 'Nov',
    subTitle: '2022',
    description: '7th Warline drop.',
  },
  {
    title: 'Dec',
    subTitle: '2022',
    description:
      'the start of implementation of the strategy developed with Kindustry.',
  },
  {
    title: 'Dec',
    subTitle: '2022',
    description:
      'free access to Ukrainian museums for NFT project owners by QR code.',
  },
  {
    title: 'After',
    subTitle: 'the victory',
    description:
      'The end of Warline and the beginning of the Renesanse collection.',
  },
  {
    title: 'After',
    subTitle: 'the victory',
    description: 'Creation of NFT agency on the basis of the project.',
  },
  {
    title: 'After',
    subTitle: 'the victory',
    description: 'Restoration of the Tereshchenko estate in Kyiv.',
  },
  {
    title: 'After',
    subTitle: 'the victory',
    description: 'Creation of the Independent Museum of Art.',
  },
];
