import { IMG_STORAGE } from '@sections/Constants';
import { AuctionCollections, AuctionItemType } from '@sections/types';

const AvatarsAuctionData: Array<Omit<AuctionItemType, 'index'>> = [
  {
    name: 'Evacuation from Bucha',
    tokenId: 1,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/AlexTwin-EvacuationFromBucha copy.jpg`,
    artist: 'Alex Twin',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: '... --- ...',
    tokenId: 2,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/AndreyRoscha-Symbols.jpg`,
    artist: 'Andrey Roscha',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Face of Glory',
    tokenId: 3,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/AndriiKharchenko-FaceOfGlory.jpg`,
    artist: 'Andrii Kharchenko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Unbroken',
    tokenId: 4,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/AnnaSova-Unbroken copy.jpg`,
    artist: 'Anna Sova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Glory',
    tokenId: 5,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/BorysKernytskyi-Glory copy.jpg`,
    artist: 'Borys Kernytskyi',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Novel Oranta',
    tokenId: 6,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/DanaVitkovska-NovelOranta copy.jpg`,
    artist: 'Dana Vitkovska',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Fight for Ukraine',
    tokenId: 7,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/DariaDemenkova-FightForUkraine copy.jpg`,
    artist: 'Daria Demenkova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Glory to Ukraine',
    tokenId: 8,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/DariaSkrypnyk-GloryToUkraine copy.jpg`,
    artist: 'Daria Skrypnyk',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Motherland Unbroken',
    tokenId: 9,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/DariaTkalenko-MotherlandUnbroken copy.jpg`,
    artist: 'Daria Tkalenko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'The Child',
    tokenId: 10,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/DenysYakovenko-TheChild copy.jpg`,
    artist: 'Denys Yakovenko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Shadows of the Ancestors',
    tokenId: 11,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/EduardKolokolov-ShadowsOfTheAncestors copy.jpg`,
    artist: 'Eduard Kolokolov',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Symbols',
    tokenId: 12,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/IhorNesterenko-Symbols copy.jpg`,
    artist: 'Ihor Nesterenko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Symbols 2',
    tokenId: 13,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/IhorNesterenko-Symbols2 copy.jpg`,
    artist: 'Ihor Nesterenko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Genocide',
    tokenId: 14,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/KarinaKuts-Genocide copy.jpg`,
    artist: 'Karina Kuts',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Mariupol',
    tokenId: 15,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/KarinaKuts-Mariupol copy.jpg`,
    artist: 'Karina Kuts',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Ukraine',
    tokenId: 16,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/KaterynaProdaivoda-Ukraine copy.jpg`,
    artist: 'Kateryna Prodaivoda',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Fight',
    tokenId: 17,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/KaterynaProdayvoda-Fight copy.jpg`,
    artist: 'Kateryna Prodayvoda',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Sorrow',
    tokenId: 18,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/KaterynaProdayvoda-Sorrow copy.jpg`,
    artist: 'Kateryna Prodayvoda',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Lo-Fi Study Girl from Ukraine',
    tokenId: 19,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/LeruteBatsian-Lo-FiStudyGirlFromUkraine copy.jpg`,
    artist: 'Lerute Batsian',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Ukrainian Women',
    tokenId: 20,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/NastyaHaidaienko-UkrainianWomen.jpg`,
    artist: 'Nastya Haidaienko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Might, Beauty and Freedom',
    tokenId: 21,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/NonnaLitvinova-MightBeautyAndFreedom copy.jpg`,
    artist: 'Nonna Litvinova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Harvest',
    tokenId: 22,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OlegShevchenko-Harvest copy.jpg`,
    artist: 'Oleg Shevchenko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'My Savior',
    tokenId: 23,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OlegZolotarenko-MySavior copy.jpg`,
    artist: 'Oleg Zolotarenko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Ukraine Will Resist',
    tokenId: 24,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OleksandrBorodin-UkraineWillResist! copy.jpg`,
    artist: 'Oleksandr Borodin',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Glory to Ukraine!',
    tokenId: 25,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OleksandrUtkin-GloryToUkraine! copy.jpg`,
    artist: 'Oleksandr Utkin',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Glory to Ukraine! Glory to the Heroes!',
    tokenId: 26,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OleksandrUtkin-GloryToUkraine!GloryToTheHeroes! copy.jpg`,
    artist: 'Oleksandr Utkin',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Ukraine',
    tokenId: 27,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OleksiiGnievyshev-Ukraine copy.jpg`,
    artist: 'Oleksii Gnievyshev',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Burning Rage',
    tokenId: 28,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OleksiiHumeniuk-BurningRage copy.jpg`,
    artist: 'Oleksii Humeniuk',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Azov Steel',
    tokenId: 29,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OleksiiRysiuk-AzovSteel copy.jpg`,
    artist: 'Oleksii Rysiuk',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Better Future',
    tokenId: 30,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OleksiiRysiuk-BetterFuture copy.jpg`,
    artist: 'Oleksii Rysiuk',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Stand with Ukraine',
    tokenId: 31,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/OlexiiSmola-StandWithUkraine copy.jpg`,
    artist: 'Olexii Smola',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Save Ukraine',
    tokenId: 32,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/Ozero__9-SaveUkraine copy.jpg`,
    artist: 'Ozero 9',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Ukraine',
    tokenId: 33,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/RomanChalyi-Ukraine copy.jpg`,
    artist: 'Roman Chalyi',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Death',
    tokenId: 34,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/RostyslavZagornov-Death copy.jpg`,
    artist: 'Rostyslav Zagornov',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'BES',
    tokenId: 35,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/Rustam-BES copy.jpg`,
    artist: 'Rustam_MrSun',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Fast Food',
    tokenId: 36,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/Rustam-FastFood copy.jpg`,
    artist: 'Rustam_MrSun',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Mariupol',
    tokenId: 37,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/SadanVague-Mariupol copy.jpg`,
    artist: 'Sadan Vague',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'St Christopher Cynocephalus',
    tokenId: 38,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/SadanVague-StChristopherCynocephalus copy.jpg`,
    artist: 'Sadan Vague',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'St Javelina',
    tokenId: 39,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/SadanVague-StJavelina copy.jpg`,
    artist: 'Sadan Vague',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Bloody Wreaths',
    tokenId: 40,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/Sandratski-BloodyWreaths copy.jpg`,
    artist: 'Sandratski',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Ukrainian Madonna',
    tokenId: 41,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/SelenisRhineNadiiaMakeienko-UkrainianMadonna copy.jpg`,
    artist: 'Selenis Rhine Nadiia Makeienko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Warm Embrace of Ukraine',
    tokenId: 42,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/Sergey-WarmEmbraceOfUkraine copy.jpg`,
    artist: 'Sergey',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'The Reaping',
    tokenId: 43,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/SerhiiHula-TheReaping copy.jpg`,
    artist: 'Serhii Hula',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Saint Javelina',
    tokenId: 44,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/StanislavLunin-SaintJavelinaSavemariupol copy.jpg`,
    artist: 'Stanislav Lunin',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Welcome to Free Ukraine',
    tokenId: 45,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/StanislavLunin-WelcomeToFreeUkraine copy.jpg`,
    artist: 'Stanislav Lunin',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Glory to Heroes!',
    tokenId: 46,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/ValeriiaKratenko-GloryToHeroes! copy.jpg`,
    artist: 'Valeriia Kratenko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Ukrainian Voluntier',
    tokenId: 47,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VitaliiIschenko-UkrainianVoluntier copy.jpg`,
    artist: 'Vitalii Ischenko',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Azovstal',
    tokenId: 48,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VladaHladkova-Azovstal copy.jpg`,
    artist: 'Vlada Hladkova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Bandura',
    tokenId: 49,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VladaHladkova-Bandura copy.jpg`,
    artist: 'Vlada Hladkova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Bucha Irpin',
    tokenId: 50,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VladaHladkova-BuchaIrpin copy.jpg`,
    artist: 'Vlada Hladkova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Hostomel',
    tokenId: 51,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VladaHladkova-Hostomel copy.jpg`,
    artist: 'Vlada Hladkova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Kherson',
    tokenId: 52,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VladaHladkova-Kherson copy.jpg`,
    artist: 'Vlada Hladkova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Mariupol',
    tokenId: 53,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VladaHladkova-Mariupol copy.jpg`,
    artist: 'Vlada Hladkova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Protection',
    tokenId: 54,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VladaHladkova-Protection copy.jpg`,
    artist: 'Vlada Hladkova',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'We will not Surrender',
    tokenId: 55,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VolodymyrBondar-WeWillNotSurrender copy.jpg`,
    artist: 'Volodymyr Bondar',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'I Want My Land to be Peaceful',
    tokenId: 56,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VolodymyrKryvonos-IWantMyLandToBePeaceful copy.jpg`,
    artist: 'Volodymyr Kryvonos',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Victory',
    tokenId: 57,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/VolodymyrSkripai-Victory copy.jpg`,
    artist: 'Volodymyr Skripai',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Children of War',
    tokenId: 58,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/Yuliia-MariiaDatsyshyn-ChildrenOfWar copy.jpg`,
    artist: 'Yuliia-Mariia Datsyshyn',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Mariupol',
    tokenId: 59,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/YuriiNahornyi-Mariupol.jpg`,
    artist: 'Yurii Nahornyi',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
  {
    name: 'Average Ukrainian Warrior',
    tokenId: 60,
    imageSrc: `${IMG_STORAGE}/original/avatars/coming-soon/YuriiRepetskyi-AverageUkrainianWarrior copy.jpg`,
    artist: 'Yurii Repetskyi',
    descriptionEnglish: '',
    descriptionUkrainian: '',
  },
].map((item) => ({
  isSale: false,
  category: AuctionCollections.avatarsForUkraine,
  ...item,
  name: 'COMING SOON',
}));

export default AvatarsAuctionData;
