import { DayType } from '@sections/types';
import { WarlineDrop } from '@pages/collections/Warline/constants';

export default [
  {
    dayNo: 37,
    date: '1 Apr 2022',
    events: [
      {
        Tokenid: '360',
        DayNo: '37',
        FullDate: '4/1/2022',
        Time: '00:09',
        TwitterUrl:
          'https://twitter.com/KyivIndependent/status/1509638737638141963',
        TwitterUsername: 'KyivIndependent',
        Headline:
          '⚡️Zelensky in a recent address to Ukrainians: "Whatever happens, we all have to think about the future, about what Ukraine will be like after this war, what our lives will be like because this is a fight for our future."',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/1.png',
      },
      {
        Tokenid: '361',
        DayNo: '37',
        FullDate: '4/1/2022',
        Time: '19:21',
        TwitterUrl:
          'https://twitter.com/IAPonomarenko/status/1509928906513653765',
        TwitterUsername: 'IAPonomarenko',
        Headline:
          'Unbelievable. Two full-fledged axes of attack just collapsed and were abandoned within 1 or 2 days. They just left having achieved nothing. We expected Russians to get entrenched to prevent Ukraine from reinforcing Donbas, but leaving completely, en masse… unbelievable.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/2.png',
      },
      {
        Tokenid: '362',
        DayNo: '37',
        FullDate: '4/1/2022',
        Time: '20:15',
        TwitterUrl:
          'https://twitter.com/JuliaDavisNews/status/1509942422490562568',
        TwitterUsername: 'uliaDavisNews',
        Headline:
          "After blaming the UK and US for Russia's war against Ukraine, the Russian lawmaker asserted that Ukraine shouldn't be allowed to exist: \"It's a cancerous growth that needs to be eliminated all the way to the border with Poland. We can't allow even a small part of it to remain.\"",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/3.png',
      },
      {
        Tokenid: '363',
        DayNo: '37',
        FullDate: '4/1/2022',
        Time: '23:24',
        TwitterUrl: 'https://twitter.com/carlbildt/status/1509990156337561610',
        TwitterUsername: 'carlbildt',
        Headline:
          'Looking back we should recognize how important it was that 🇱🇹 🇱🇻 🇪🇪 were able to join NATO nearly two decades ago. If they today had been outside in some sort of grey zone, there would have been an imminent danger of them become part of a war zone. Now, NATO gives them security.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/4.png',
      },
    ],
  },
  {
    dayNo: 38,
    date: '2 Apr 2022',
    events: [
      {
        Tokenid: '364',
        DayNo: '38',
        FullDate: '4/2/2022',
        Time: '01:45',
        TwitterUrl:
          'https://twitter.com/lesiavasylenko/status/1510025708223049735',
        TwitterUsername: 'lesiavasylenko',
        Headline:
          'At 28 Natalia flew fighter jets. First woman-pilot in the #Ukraine Air Force. She gave her life for Ukraine. A true Ukrainian Super Woman',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/5.png',
      },
      {
        Tokenid: '365',
        DayNo: '38',
        FullDate: '4/2/2022',
        Time: '01:32',
        TwitterUrl: 'https://twitter.com/JoeBiden/status/1510022194214182914',
        TwitterUsername: 'JoeBiden',
        Headline:
          'Last week, I met with NATO allies to reiterate our strong support for the Ukrainian people. Putin was banking on NATO being divided, but it has never been more united than it is today.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/6.png',
      },
      {
        Tokenid: '366',
        DayNo: '38',
        FullDate: '4/2/2022',
        Time: '23:57',
        TwitterUrl:
          'https://twitter.com/HillelNeuer/status/1510360679651360771',
        TwitterUsername: 'HillelNeuer',
        Headline:
          "For God's sake, Russia cannot remain on the U.N. Human Rights Council.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/7.png',
      },
    ],
  },
  {
    dayNo: 39,
    date: '3 Apr 2022',
    events: [
      {
        Tokenid: '367',
        DayNo: '39',
        FullDate: '4/3/2022',
        Time: '02:07',
        TwitterUrl:
          'https://twitter.com/anders_aslund/status/1510393419461398528',
        TwitterUsername: 'anders_aslund',
        Headline:
          'Do Macron and Scholz still consider it permissible to talk to mass murderer and patent liar Putin? If so, why?',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/8.png',
      },
      {
        Tokenid: '368',
        DayNo: '39',
        FullDate: '4/3/2022',
        Time: '02:07',
        TwitterUrl:
          'https://twitter.com/IAPonomarenko/status/1510394069926748169',
        TwitterUsername: 'IAPonomarenko',
        Headline:
          'Just fucking image how many people they have executed in Mariupol. In my Volnovakha, and all those cities and towns Russia razed to the ground. One giant insane bloodbath, WWII-scale, for the sake of sick fantasies of “denazification” leaving thousands of dead bodies behind.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/9.png',
      },
      {
        Tokenid: '369',
        DayNo: '39',
        FullDate: '4/3/2022',
        Time: '02:56',
        TwitterUrl:
          'https://twitter.com/LatestAnonPress/status/1510405901676650497',
        TwitterUsername: 'LatestAnonPress',
        Headline:
          'It looks like scenes from a horror movie. But it is not! This is the result of the murders of hundreds of civilians by Russian soldiers in Ukraine, in the town of #Bucha near #Kyiv. PUTIN NEEDS TO BE STOPPED NOW!',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/10.png',
      },
      {
        Tokenid: '370',
        DayNo: '39',
        FullDate: '4/3/2022',
        Time: '21:30',
        TwitterUrl:
          'https://twitter.com/kylegriffin1/status/1510686067564838915',
        TwitterUsername: 'kylegriffin1',
        Headline:
          'Reuters: Ukraine says its forces have retaken all areas around the capital, reclaiming complete control of the region for the first time since Russia invaded on Feb. 24.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/11.png',
      },
      {
        Tokenid: '371',
        DayNo: '39',
        FullDate: '4/3/2022',
        Time: '21:48',
        TwitterUrl: 'https://twitter.com/McFaul/status/1510690663007809536',
        TwitterUsername: 'McFaul',
        Headline:
          "Putin's barbaric killing in Bucha requires new sanctions immediately — oil and gas sanctions; all Russian banks out of Swift; all US companies out of Russia,  by the end of the week.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/12.png',
      },
    ],
  },
  {
    dayNo: 40,
    date: '4 Apr 2022',
    events: [
      {
        Tokenid: '372',
        DayNo: '40',
        FullDate: '4/4/2022',
        Time: '00:02',
        TwitterUrl: 'https://twitter.com/Kasparov63/status/1510724560173289472',
        TwitterUsername: 'Kasparov63',
        Headline:
          "The latest horrors out of Putin's war on Ukraine put the remaining Western holdouts against stronger action in an unbearable position. Excuses are now complicity, not prudence, not just cowardice.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/13.png',
      },
      {
        Tokenid: '373',
        DayNo: '40',
        FullDate: '4/4/2022',
        Time: '01:42',
        TwitterUrl:
          'https://twitter.com/lesiavasylenko/status/1510749611174109193',
        TwitterUsername: 'lesiavasylenko',
        Headline:
          'Russian soldiers loot, rape and kill. 10 y.o. girls with vaginal and rectal tears. Women with swastika shaped burns. Russia. Russian Men did this. And Russian mothers raised them. A nation of immoral criminals',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/14.png',
      },
      {
        Tokenid: '374',
        DayNo: '40',
        FullDate: '4/4/2022',
        Time: '22:18',
        TwitterUrl: 'https://twitter.com/nytimes/status/1511060668610457612',
        TwitterUsername: 'nytimes',
        Headline:
          "Breaking News: Satellite images refute Russia’s claim that the killing of civilians in Bucha, a suburb of Ukraine's capital, occurred after its soldiers had left town, a New York Times analysis found.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/15.png',
      },
      {
        Tokenid: '375',
        DayNo: '40',
        FullDate: '4/4/2022',
        Time: '22:30',
        TwitterUrl:
          'https://twitter.com/IAPonomarenko/status/1511063563028283398',
        TwitterUsername: 'IAPonomarenko',
        Headline:
          'Upon my rough estimates, Russia in fact has withdrawn from nearly 40% (!) of the territories it occupied in Ukraine since February 24. Within just 2 or 3 days. The whole of Kyiv, Chernihiv, Sumy regions. The war’s phase 1 ends with Russia’s crushing defeat. Now phase 2 begins.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/16.png',
      },
    ],
  },
  {
    dayNo: 41,
    date: '5 Apr 2022',
    events: [
      {
        Tokenid: '376',
        DayNo: '41',
        FullDate: '4/5/2022',
        Time: '01:51',
        TwitterUrl:
          'https://twitter.com/KatyaYushchenko/status/1511114253213872134',
        TwitterUsername: 'KatyaYushchenko',
        Headline:
          'I cannot get over the courage of the people of Kherson, who keep going out on the streets demanding that the occupiers leave and declaring “Kherson is Ukraine”.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/17.png',
      },
      {
        Tokenid: '377',
        DayNo: '41',
        FullDate: '4/5/2022',
        Time: '21:56',
        TwitterUrl: 'https://twitter.com/visegrad24/status/1511417420220665861',
        TwitterUsername: 'visegrad24',
        Headline:
          'The Czech Republic has become the first country to donate tanks to Ukraine. Czech Deputy Defense Minister Tomáš Kopečný says that the country has sent more than a dozen modernized, Soviet-designed T-72M tanks. Time for NATO to send those S-300s and MiG-29s too! 🇨🇿🇺🇦',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/18.png',
      },
      {
        Tokenid: '378',
        DayNo: '41',
        FullDate: '4/5/2022',
        Time: '23:46',
        TwitterUrl:
          'https://twitter.com/ZelenskyyUa/status/1511445189054894086',
        TwitterUsername: 'ZelenskyyUa',
        Headline:
          'Russian atrocities in the Kyiv region must be investigated and Russia itself must face new painful sanctions. Discussed that with @EmmanuelMacron We also talked about negotiations and humanitarian aid to the blocked 🇺🇦 cities. Thank you, my friend, for your principled position.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/19.png',
      },
    ],
  },
  {
    dayNo: 42,
    date: '6 Apr 2022',
    events: [
      {
        Tokenid: '379',
        DayNo: '42',
        FullDate: '4/6/2022',
        Time: '12:31',
        TwitterUrl:
          'https://twitter.com/KyivIndependent/status/1511456568348487682',
        TwitterUsername: 'KyivIndependent',
        Headline:
          '⚡️ Estonia sends lethal weapons to Ukraine. Estonia has handed over to Ukraine anti-tank missiles and mines, automatic weapons, ammunition, disposable grenades and hand grenades.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/20.png',
      },
      {
        Tokenid: '380',
        DayNo: '42',
        FullDate: '4/6/2022',
        Time: '16:27',
        TwitterUrl: 'https://twitter.com/Pontifex/status/1511697165105651713',
        TwitterUsername: 'Pontifex',
        Headline:
          'Новости с Украины  свидетельствуют о новых зверствах, таких как резня в Буче: всё более чудовищная жестокость, также в отношении беззащитных гражданских лиц, женщин и детей. #Украина',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/21.png',
      },
      {
        Tokenid: '381',
        DayNo: '42',
        FullDate: '4/6/2022',
        Time: '17:40',
        TwitterUrl: 'https://twitter.com/potus/status/1511715451738464256',
        TwitterUsername: 'POTUS',
        Headline:
          ' I made clear that Russia would pay a severe and immediate price for its atrocities in Bucha. Today, along with our Allies and partners, we’re announcing a new round of devastating sanctions.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/22.png',
      },
      {
        Tokenid: '382',
        DayNo: '42',
        FullDate: '4/6/2022',
        Time: '19:50',
        TwitterUrl: 'https://twitter.com/McFaul/status/1511748076729352192',
        TwitterUsername: 'McFaul',
        Headline:
          'The best way to avoid a conflict between NATO and Russia in the future is to help Ukraine stop Putins killing machine in Ukraine now. It is really that simple. A Putin loss in Ukraine makes conflict with NATO less likely. A Putin win makes conflict with NATO more likely.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/23.png',
      },
    ],
  },
  {
    dayNo: 43,
    date: '7 Apr 2022',
    events: [
      {
        Tokenid: '383',
        DayNo: '43',
        FullDate: '4/7/2022',
        Time: '18:52',
        TwitterUrl:
          'https://twitter.com/DmytroKuleba/status/1512095879037169665',
        TwitterUsername: 'DmytroKuleba',
        Headline:
          'Russia’s rights of membership in the UN Human Rights Council has just been suspended. War criminals have no place in UN bodies aimed at protecting human rights. Grateful to all member states which supported the relevant UNGA resolution and chose the right side of history.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/24.png',
      },
      {
        Tokenid: '384',
        DayNo: '43',
        FullDate: '4/7/2022',
        Time: '22:42',
        TwitterUrl:
          'https://twitter.com/IAPonomarenko/status/1512143723286736896',
        TwitterUsername: 'IAPonomarenko',
        Headline:
          'CBS asked me today live why I wanted to quit doing war journalism after the end of the war. This is why. Because of this guy’s picture in her mom’s Instagram. 4-year-old Sasha went missing amid hostilities near Kyiv. Later, they found his body in the Kyiv Sea.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/25.png',
      },
      {
        Tokenid: '385',
        DayNo: '43',
        FullDate: '4/7/2022',
        Time: '22:59',
        TwitterUrl:
          'https://twitter.com/den_kazansky/status/1512158186882666503',
        TwitterUsername: 'den_kazansky',
        Headline:
          'Это я стою на дне воронки от авиабомбы, которую сбросили на село Новоселовка под Черниговом. Село практически разрушено авиаударами.  Россия ведёт с украинским народом войну на уничтожение. И это не просто громкие слова. Достаточно просто взглянуть на фото, чтобы это понять',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/26.png',
      },
    ],
  },
  {
    dayNo: 44,
    date: '8 Apr 2022',
    events: [
      {
        Tokenid: '386',
        DayNo: '44',
        FullDate: '4/8/2022',
        Time: '21:01',
        TwitterUrl: 'https://twitter.com/U2/status/1512490783068274695',
        TwitterUsername: 'U2',
        Headline:
          'The brave people of Ukraine are fighting for their freedom -- and for ours -- in the face of unspeakable violence and an unjust invasion. More than 4 million people, mostly women and children, have had to flee for their lives -- a population nearly the size of Ireland.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/27.png',
      },
      {
        Tokenid: '387',
        DayNo: '44',
        FullDate: '4/8/2022',
        Time: '11:14',
        TwitterUrl:
          'https://twitter.com/vonderleyen/status/1512524318651076610',
        TwitterUsername: 'vonderleyen',
        Headline:
          'We can never match the sacrifice of the Ukrainian people. But we are mobilizing our economic power to make Putin pay. We have imposed heavy sanctions against Russia & are already preparing the 6th wave. Russia will descend, while Ukraine is marching towards a European future.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/28.png',
      },
      {
        Tokenid: '388',
        DayNo: '44',
        FullDate: '4/8/2022',
        Time: '11:33',
        TwitterUrl: 'https://twitter.com/MaxRTucker/status/1512529009661419530',
        TwitterUsername: 'MaxRTucker',
        Headline:
          '121,000 Ukrainian children have been forcibly removed to Russia, Ukraine’s Ombudswoman says. Now Moscow plans to simplify the procedure for Russians to adopt these children, potentially separating them from their families forever. This calculated cruelty is astounding.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/29.png',
      },
    ],
  },
  {
    dayNo: 45,
    date: '9 Apr 2022',
    events: [
      {
        Tokenid: '389',
        DayNo: '45',
        FullDate: '4/9/2022',
        Time: '17:28',
        TwitterUrl:
          'https://twitter.com/vonderleyen/status/1512799522128285696',
        TwitterUsername: 'vonderleyen',
        Headline:
          'Today we raised 9.1 billion euros for the people fleeing the invasion, inside Ukraine and abroad. And more will come! We will continue providing support. And once the bombs have stopped falling, we will help the people of Ukraine rebuild their country.  #StandUpForUkraine',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/30.png',
      },
      {
        Tokenid: '390',
        DayNo: '45',
        FullDate: '4/9/2022',
        Time: '18:42',
        TwitterUrl:
          'https://twitter.com/BorisJohnson/status/1512818337415372802',
        TwitterUsername: 'BorisJohnson',
        Headline:
          "Today I met my friend President @ZelenskyyUa in Kyiv as a show of our unwavering support for the people of Ukraine. We're setting out a new package of financial & military aid which is a testament of our commitment to his country's struggle against Russia’s barbaric campaign.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/31.png',
      },
      {
        Tokenid: '391',
        DayNo: '45',
        FullDate: '4/9/2022',
        Time: '21:58',
        TwitterUrl: 'https://twitter.com/berlusconi/status/1512867688296718337',
        TwitterUsername: 'berlusconi',
        Headline:
          "Bisogna fare tutto il possibile perché tutto questo finisca, per mettere fine alla brutalità della guerra e l'Italia deve lavorare a questo, perché si arrivi ad un compromesso accettabile da tutti. Questo significa che la libertà e l'integrità dell'Ucraina devono essere garantite",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/32.png',
      },
    ],
  },
  {
    dayNo: 46,
    date: '10 Apr 2022',
    events: [
      {
        Tokenid: '392',
        DayNo: '46',
        FullDate: '4/10/2022',
        Time: '23:47',
        TwitterUrl:
          'https://twitter.com/amyklobuchar/status/1513257296419250189',
        TwitterUsername: 'amyklobuchar',
        Headline:
          'Vladimir Putin has shown us new depths of evil. No one can remain silent. The 🌎 must stand with Ukraine 🇺🇦',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/33.png',
      },
    ],
  },
  {
    dayNo: 47,
    date: '11 Apr 2022',
    events: [
      {
        Tokenid: '393',
        DayNo: '47',
        FullDate: '4/11/2022',
        Time: '19:52',
        TwitterUrl:
          'https://twitter.com/WalshFreedom/status/1513560730968145920',
        TwitterUsername: 'WalshFreedom',
        Headline: 'Because of Putin, NATO will expand.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/34.png',
      },
      {
        Tokenid: '394',
        DayNo: '47',
        FullDate: '4/11/2022',
        Time: '22:43',
        TwitterUrl:
          'https://twitter.com/KyivIndependent/status/1513603720646467589',
        TwitterUsername: 'KyivIndependent',
        Headline:
          "⚡️⚡️Azov regiment: Russia used poisonous substance against Ukrainian troops in Mariupol. The substance has been distributed by a drone, and victims have shortness of breath and vestibulocerebellar ataxia. It may be Russia's first known use of chemical weapons in Ukraine.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/35.png',
      },
      {
        Tokenid: '395',
        DayNo: '47',
        FullDate: '4/11/2022',
        Time: '22:44',
        TwitterUrl:
          'https://twitter.com/den_kazansky/status/1513604040097214465',
        TwitterUsername: 'den_kazansky',
        Headline:
          'Россия применила в Мариуполе химическое оружие. Сегодня подконтрольные Кремлю боевики открыто анонсировали химическую атаку на российском телевидении. И воплотили свои угрозы в жизнь. Уже можно не стесняться и менять Z на настоящую свастику. Открыто перешли к методам нацистов',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/36.png',
      },
      {
        Tokenid: '396',
        DayNo: '47',
        FullDate: '4/11/2022',
        Time: '22:59',
        TwitterUrl:
          'https://twitter.com/olgatokariuk/status/1513607810004701192',
        TwitterUsername: 'olgatokariuk',
        Headline:
          'Mariupol siege and total annihilation of the city by Russians should have been a turning point. Bucha massacre should have definitely been a game changer. They were not. Will the use of chemical weapons by Russia be? How many more #RussianWarCrimes will the world tolerate?',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/37.png',
      },
    ],
  },
  {
    dayNo: 48,
    date: '12 Apr 2022',
    events: [
      {
        Tokenid: '397',
        DayNo: '48',
        FullDate: '4/12/2022',
        Time: '01:15',
        TwitterUrl: 'https://twitter.com/SamRamani2/status/1513641815936843781',
        TwitterUsername: 'SamRamani2',
        Headline:
          'BREAKING: Germany could ship up to 50 Leopard 1 battle tanks to Ukraine in 6 weeks',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/38.png',
      },
      {
        Tokenid: '398',
        DayNo: '48',
        FullDate: '4/12/2022',
        Time: '19:36',
        TwitterUrl: 'https://twitter.com/McFaul/status/1513919061914136580',
        TwitterUsername: 'McFaul',
        Headline:
          'Listen closely. Putin does not  mention NATO expansion at all in his explanation for why he invaded. Not once.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/39.png',
      },
      {
        Tokenid: '399',
        DayNo: '48',
        FullDate: '4/12/2022',
        Time: '21:25',
        TwitterUrl:
          'https://twitter.com/IAPonomarenko/status/1513946349632376833',
        TwitterUsername: 'IAPonomarenko',
        Headline:
          'Are.You. Just. Kidding. Me?!! Viktor Medvedchuk, Putin’s main man in Ukraine, busted as a result of a Ukrainian spec op.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/40.png',
      },
    ],
  },
  {
    dayNo: 49,
    date: '13 Apr 2022',
    events: [
      {
        Tokenid: '400',
        DayNo: '49',
        FullDate: '4/13/2022',
        Time: '00:15',
        TwitterUrl: 'https://twitter.com/POTUS/status/1513989084598972419',
        TwitterUsername: 'POTUS',
        Headline:
          'Putin’s invasion of Ukraine has driven up gas prices and food prices all over the world. 70% of the increase in prices in March came from the Putin Price Hike. I’m doing everything I can to bring down prices and address the Putin Price Hike.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/41.png',
      },
      {
        Tokenid: '401',
        DayNo: '49',
        FullDate: '4/13/2022',
        Time: '01:38',
        TwitterUrl:
          'https://twitter.com/ZelenskyyUa/status/1514010150193008652',
        TwitterUsername: 'ZelenskyyUa',
        Headline:
          'Справжні слова справжнього лідера @POTUS. Називати речі своїми іменами важливо, щоб протистояти злу. Ми вдячні за допомогу, яку США вже надали, і терміново потребуємо більше важкого озброєння, щоб запобігти подальшим звірствам Росії.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/42.png',
      },
      {
        Tokenid: '402',
        DayNo: '49',
        FullDate: '4/13/2022',
        Time: '02:28',
        TwitterUrl: 'https://twitter.com/SamRamani2/status/1514022675533942785',
        TwitterUsername: 'SamRamani2',
        Headline:
          'Zelensky reminded Russia that its 48 hour war with Ukraine has already lasted 48 days',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/43.png',
      },
      {
        Tokenid: '403',
        DayNo: '49',
        FullDate: '4/13/2022',
        Time: '23:29',
        TwitterUrl: 'https://twitter.com/POTUS/status/1514339982407831557',
        TwitterUsername: 'POTUS',
        Headline:
          'Today, I spoke with President Zelenskyy and shared with him that my Administration is authorizing an additional $800 million in weapons, ammunition, and other security assistance to Ukraine.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/44.png',
      },
    ],
  },
  {
    dayNo: 50,
    date: '14 Apr 2022',
    events: [
      {
        Tokenid: '404',
        DayNo: '50',
        FullDate: '4/14/2022',
        Time: '20:32',
        TwitterUrl: 'https://twitter.com/SeanPenn/status/1514657810423840768',
        TwitterUsername: 'SeanPenn',
        Headline:
          "Let's unite to stop the war in Ukraine. Let's defend freedom and save lives. We ask world leaders to #ArmUkraineNow.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/45.png',
      },
      {
        Tokenid: '405',
        DayNo: '50',
        FullDate: '4/14/2022',
        Time: '22:51',
        TwitterUrl:
          'https://twitter.com/ZelenskyyUa/status/1514692962021691402',
        TwitterUsername: 'ZelenskyyUa',
        Headline:
          'Held negotiations with 🇫🇷 President @EmmanuelMacron. Discussed the investigation of Russian crimes, the resistance of 🇺🇦 people to the invader. We appreciate the strong support of 🇫🇷. The negotiation process was also discussed. We strive for peace in Ukraine, in Europe!',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/46.png',
      },
      {
        Tokenid: '406',
        DayNo: '50',
        FullDate: '4/14/2022',
        Time: '23:21',
        TwitterUrl:
          'https://twitter.com/IAPonomarenko/status/1514700413970395145',
        TwitterUsername: 'IAPonomarenko',
        Headline:
          'BREAKING ⚡️⚡️⚡️ Russian Black Sea Fleet flagship Moskva confirmed sank. The first Russian loss of a flagship since the Russian-Japanese war of 1904-1905. A historic Ukrainian victory.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/47.png',
      },
    ],
  },
  {
    dayNo: 51,
    date: '15 Apr 2022',
    events: [
      {
        Tokenid: '407',
        DayNo: '51',
        FullDate: '4/15/2022',
        Time: '01:43',
        TwitterUrl:
          'https://twitter.com/lesiavasylenko/status/1514736227966148608',
        TwitterUsername: 'lesiavasylenko',
        Headline:
          '3 explosions in #Kyiv right now. One after the other. The air raid warning has been on for an hour. Most likely #putin gone livid because of the #Moskva sinking. Oh well, we’ll just keep standing to #Russia’s annoyance',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/48.png',
      },
      {
        Tokenid: '408',
        DayNo: '51',
        FullDate: '4/15/2022',
        Time: '19:27',
        TwitterUrl: 'https://twitter.com/BrianKarem/status/1515003892718878722',
        TwitterUsername: 'BrianKarem',
        Headline:
          'NOW: Ukraine seizes 32 apartments, 55 homes, 26 cars and yacht from Pro-Putin mogul Medvedchuk.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/49.png',
      },
      {
        Tokenid: '409',
        DayNo: '51',
        FullDate: '4/15/2022',
        Time: '20:34',
        TwitterUrl: 'https://twitter.com/Podolyak_M/status/1515020631066255368',
        TwitterUsername: 'Podolyak_M',
        Headline:
          'It was Russia that started an unprovoked war on foreign territory. With mass deliberate killings of civilians and large-scale destruction of civilian infrastructure. Therefore, any retaliatory actions of Ukraine are both morally and legally absolutely justified.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/50.png',
      },
      {
        Tokenid: '410',
        DayNo: '51',
        FullDate: '4/15/2022',
        Time: '21:00',
        TwitterUrl: 'https://twitter.com/SamRamani2/status/1515027261518458887',
        TwitterUsername: 'SamRamani2',
        Headline:
          'Zelensky reportedly asked Biden to designate Russia as a state sponsor of terrorism. Iran, Syria, North Korea and Cuba are sanctioned under this designation.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/51.png',
      },
    ],
  },
  {
    dayNo: 52,
    date: '16 Apr 2022',
    events: [
      {
        Tokenid: '411',
        DayNo: '52',
        FullDate: '4/16/2022',
        Time: '01:37',
        TwitterUrl: 'https://twitter.com/SamRamani2/status/1515097018137513986',
        TwitterUsername: 'SamRamani2',
        Headline:
          'BREAKING: Germany plans to release more than a billion euros in military aid to Ukraine',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/52.png',
      },
      {
        Tokenid: '412',
        DayNo: '52',
        FullDate: '4/16/2022',
        Time: '02:46',
        TwitterUrl:
          'https://twitter.com/anders_aslund/status/1515114294416969732',
        TwitterUsername: 'anders_aslund',
        Headline:
          'My gut feeling is that Putin cannot win his war against Ukraine. He has no cause. He has made every mistake in the book. Now he arrests everybody for the mistakes he himself has made. Besides, he has destroyed the Russian economy and its institutions. What a loser!',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/53.png',
      },
      {
        Tokenid: '413',
        DayNo: '52',
        FullDate: '4/16/2022',
        Time: '18:15',
        TwitterUrl:
          'https://twitter.com/CurrentTimeTv/status/1515348095445487630',
        TwitterUsername: 'CurrentTimeTv',
        Headline:
          '"Что, сука, сделал им этот 12-летний мальчик?" Утром 16 апреля Россия снова обстреляла ракетами Харьков, есть погибший, 18 человек ранены. Посмотрите, как врачи "скорой" забирают раненых из сквера: мужчина рассказывает, что его друг погиб на месте, а 12-летний подросток был ранен',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/54.png',
      },
      {
        Tokenid: '414',
        DayNo: '52',
        FullDate: '4/16/2022',
        Time: '20:17',
        TwitterUrl:
          'https://twitter.com/BorisJohnson/status/1515378969251569668',
        TwitterUsername: 'BorisJohnson',
        Headline:
          'I updated my friend @ZelenskyyUa this afternoon on further military aid we will provide to Ukraine in the coming days. The UK will stop at nothing to ensure Ukrainians have the resources they need to defend their country from the ongoing Russian onslaught. #StandWithUkraine️',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/55.png',
      },
      {
        Tokenid: '415',
        DayNo: '52',
        FullDate: '4/16/2022',
        Time: '20:22',
        TwitterUrl: 'https://twitter.com/JackDetsch/status/1515380118130155536',
        TwitterUsername: 'JackDetsch',
        Headline:
          'NEW: Ukrainian troops have killed Russian Maj. Gen. Vladimir Frolov, deputy commander of the Eighth Army: Russian state media reports. Frolov would be the 8th Russian General killed in Ukraine in 51 days of war.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/56.png',
      },
    ],
  },
  {
    dayNo: 53,
    date: '17 Apr 2022',
    events: [
      {
        Tokenid: '416',
        DayNo: '53',
        FullDate: '4/17/2022',
        Time: '01:35',
        TwitterUrl: 'https://twitter.com/davidfrum/status/1515458966024818692',
        TwitterUsername: 'davidfrum',
        Headline:
          'If Russia should lose its war against Ukraine, not only will Ukraine secure its full post-Soviet independence - but NATO, the EU, and western democracies generally will be strengthened. So it\'s not "unprincipled" for people who dislike western democracy & lament the USSR ...',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/57.png',
      },
      {
        Tokenid: '417',
        DayNo: '53',
        FullDate: '4/17/2022',
        Time: '17:58',
        TwitterUrl:
          'https://twitter.com/SvobodaRadio/status/1515706197286047748',
        TwitterUsername: 'SvobodaRadio',
        Headline:
          'Владимир Зеленский заявил в интервью CNN, что Украина не готова отдать России территории на востоке страны ради окончания войны. Сражение в Донбассе может повлиять на ход всей войны, и Украина готова к нему, добавил Зеленский',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/58.png',
      },
      {
        Tokenid: '418',
        DayNo: '53',
        FullDate: '4/17/2022',
        Time: '22:22',
        TwitterUrl:
          'https://twitter.com/anders_aslund/status/1515772801705205771',
        TwitterUsername: 'anders_aslund',
        Headline:
          "Let me look forward optimistically: 1. Putin's war on Ukraine is WORSE than the Russo-Japanese war of 1904-5 for the Russian regime. 2. My guess is that Russia will have to give up all its territories in Ukraine & face total defeat. 3. No Russian leader can survive such a defeat.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/59.png',
      },
      {
        Tokenid: '419',
        DayNo: '53',
        FullDate: '4/17/2022',
        Time: '23:06',
        TwitterUrl: 'https://twitter.com/Ukraine/status/1515783801456181259',
        TwitterUsername: 'Ukraine',
        Headline:
          'Mariupol had lived in peace before Russia invaded, ruined 95% of the city by heavy bombardment, and killed thousands of people. Ukrainian forces still hold on. Wounded and dead need evacuation. So are thousands of civilians, including kids and elderly. People lack food and water.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/60.png',
      },
    ],
  },
  {
    dayNo: 54,
    date: '18 Apr 2022',
    events: [
      {
        Tokenid: '420',
        DayNo: '54',
        FullDate: '4/18/2022',
        Time: '00:13',
        TwitterUrl:
          'https://twitter.com/KyivIndependent/status/1515800624083918852',
        TwitterUsername: 'KyivIndependent',
        Headline:
          "⚡️ Intelligence chief: Putin unlikely to use nuclear weapons.The Russian dictator's nuclear threats are blackmail, and the use of nuclear weapons is technically difficult, Kyrylo Budanov, head of Ukraine's military intelligence, said on April 17.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/61.jpg',
      },
      {
        Tokenid: '421',
        DayNo: '54',
        FullDate: '4/18/2022',
        Time: '00:19',
        TwitterUrl:
          'https://twitter.com/chefjoseandres/status/1515802156196106241',
        TwitterUsername: 'chefjoseandres',
        Headline:
          'A message for you from Ukraine on this Holy day… In our dark hour I see a future of light. Every day I see the unity & spirit of the Ukrainian people and that is worth celebrating! And @WCKitchen will keep fighting to ensure a plate of food is the start of a better tomorrow… 🇺🇦',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/62.jpg',
      },
      {
        Tokenid: '422',
        DayNo: '54',
        FullDate: '4/18/2022',
        Time: '18:02',
        TwitterUrl:
          'https://twitter.com/olgatokariuk/status/1516069565142380557',
        TwitterUsername: 'olgatokariuk',
        Headline:
          'Russia launched a millions of dollars-worth Kalibr missile on Lviv to hit a car repair shop. Why? To kill civilians (7 people died),to show that nowhere in Ukraine is safe. And also because it can, because it feels total impunity that no one has courage to #ClosetheSkyoverUkraine',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/63.jpg',
      },
      {
        Tokenid: '423',
        DayNo: '54',
        FullDate: '4/18/2022',
        Time: '20:18',
        TwitterUrl: 'https://twitter.com/BrianKarem/status/1516104008821350410',
        TwitterUsername: 'BrianKarem',
        Headline:
          "NOW: Putin's intelligence apparatus continues to stumble from a major Kremlin breach after Ukraine publishes the names and numbers of 620 Kremlin spies, rendering them potentially unusable.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/64.jpg',
      },
      {
        Tokenid: '424',
        DayNo: '54',
        FullDate: '4/18/2022',
        Time: '20:45',
        TwitterUrl:
          'https://twitter.com/UnitedNationsRU/status/1516110560810598400',
        TwitterUsername: 'UnitedNationsRU',
        Headline:
          'Даже ограниченная ядерная война регионального масштаба спровоцирует значительную дезорганизацию климата, которая вызовет порожденный ядерным оружием голод, которым будет охвачено более 2 млрд человек. Медики и сотрудники оперативных служб не смогут работать в загрязненных районах',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/65.jpg',
      },
    ],
  },
  {
    dayNo: 55,
    date: '19 Apr 2022',
    events: [
      {
        Tokenid: '425',
        DayNo: '55',
        FullDate: '4/19/2022',
        Time: '17:45',
        TwitterUrl:
          'https://twitter.com/LorenzoTheCat/status/1516427796939169811',
        TwitterUsername: 'LorenzoTheCat',
        Headline:
          "The man's name is Eugene Kibets. He's a Ukrainian from Kyiv who has been rescuing animals that have lost their owners due to the war. He's a good man. ❤️🐱🇺🇦",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/66.jpg',
      },
      {
        Tokenid: '426',
        DayNo: '55',
        FullDate: '4/19/2022',
        Time: '20:21',
        TwitterUrl:
          'https://twitter.com/AuschwitzMuseum/status/1516466983075823626',
        TwitterUsername: 'AuschwitzMuseum',
        Headline:
          'At 10 years old, Vanda Semyonovna Obiedkova survived the Germans by hiding in a basement in Mariupol. 81 years later, she died in a basement in the same city as a victim of the horrific war hiding from the Russians.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/67.jpg',
      },
      {
        Tokenid: '427',
        DayNo: '55',
        FullDate: '4/19/2022',
        Time: '21:03',
        TwitterUrl:
          'https://twitter.com/kaitlancollins/status/1516477527866458119',
        TwitterUsername: 'kaitlancollins',
        Headline:
          'President Biden says he plans to send more artillery to Ukraine.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/68.jpg',
      },
    ],
  },
  {
    dayNo: 56,
    date: '20 Apr 2022',
    events: [
      {
        Tokenid: '428',
        DayNo: '56',
        FullDate: '4/20/2022',
        Time: '00:59',
        TwitterUrl:
          'https://twitter.com/KyivIndependent/status/1516537037297532934',
        TwitterUsername: 'KyivIndependent',
        Headline:
          "⚡️Zelensky: 'If we had access to all the weapons we need, which our partners have, we would have already ended this war.' Zelensky renewed calls for weapons to Ukraine, saying “it is unfair that Ukraine is still forced to ask for what its partners have been storing for years.”",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/69.jpg',
      },
      {
        Tokenid: '429',
        DayNo: '56',
        FullDate: '4/20/2022',
        Time: '02:34',
        TwitterUrl: 'https://twitter.com/mrsorokaa/status/1516560940539555844',
        TwitterUsername: 'mrsorokaa',
        Headline:
          'Russian war against Ukraine is a genocide. Kyiv is willing to evacuate civilians and soldiers from Mariupol, soldiers are ready to leave if they are allowed a safe passage, Moscow would save its own soldiers and take the strategic city. But Russia says no, Russia wants blood.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/70.jpg',
      },
      {
        Tokenid: '430',
        DayNo: '56',
        FullDate: '4/20/2022',
        Time: '19:58',
        TwitterUrl: 'https://twitter.com/McFaul/status/1516823596873617415',
        TwitterUsername: 'McFaul',
        Headline:
          'In his invasion of Ukraine, Putin has pursued many war objectives. So far, he has achieved none. 1/ THREAD',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/71.jpg',
      },
    ],
  },
  {
    dayNo: 57,
    date: '21 Apr 2022',
    events: [
      {
        Tokenid: '431',
        DayNo: '57',
        FullDate: '4/21/2022',
        Time: '18:28',
        TwitterUrl: 'https://twitter.com/SamRamani2/status/1517163351498964992',
        TwitterUsername: 'SamRamani2',
        Headline:
          'BREAKING: Spain has sent 200 tons of military equipment to Ukraine including heavy transport vehicles and ammunition',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/72.jpg',
      },
      {
        Tokenid: '432',
        DayNo: '57',
        FullDate: '4/21/2022',
        Time: '18:45',
        TwitterUrl: 'https://twitter.com/POTUS/status/1517167525708111873',
        TwitterUsername: 'POTUS',
        Headline:
          'Today, I am announcing another $800 million to further augment Ukraine’s ability to fight in the East. This package will include heavy artillery weapons, dozens of howitzers, and 144,000 rounds of ammunition to go with them. It also includes more tactical drones.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/73.jpg',
      },
      {
        Tokenid: '433',
        DayNo: '57',
        FullDate: '4/21/2022',
        Time: '20:23',
        TwitterUrl: 'https://twitter.com/BrianKarem/status/1517192222441369600',
        TwitterUsername: 'BrianKarem',
        Headline:
          "NOW: In the latest blow to Putin's economy, the United States will ban all Russian ships from U.S. ports in retaliation for the war in Ukraine.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/74.jpg',
      },
    ],
  },
  {
    dayNo: 58,
    date: '22 Apr 2022',
    events: [
      {
        Tokenid: '434',
        DayNo: '58',
        FullDate: '4/22/2022',
        Time: '02:45',
        TwitterUrl: 'https://twitter.com/POTUS/status/1517288322875502593',
        TwitterUsername: 'POTUS',
        Headline:
          'As Russia continues to grind out brutalities against Ukraine, Putin is banking on us losing interest. He is betting that Western unity will crack. Once again, we will prove him wrong.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/75.jpg',
      },
      {
        Tokenid: '435',
        DayNo: '58',
        FullDate: '4/22/2022',
        Time: '21:32',
        TwitterUrl: 'https://twitter.com/DefenceU/status/1517572067125825536',
        TwitterUsername: 'DefenceU',
        Headline:
          'This is Maryna. She is one of 386 🇺🇦 children injured by russian aggression. 208 more have been killed by russian war criminals. Children are the future which we are now fighting for with our lives. Give us an opportunity protect it. Close the sky! #ArmUkraineNow',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/76.jpg',
      },
    ],
  },
  {
    dayNo: 59,
    date: '23 Apr 2022',
    events: [
      {
        Tokenid: '436',
        DayNo: '59',
        FullDate: '4/23/2022',
        Time: '02:30',
        TwitterUrl:
          'https://twitter.com/NikaMelkozerova/status/1517828342367637504',
        TwitterUsername: 'NikaMelkozerova',
        Headline:
          'Russians have deported more than 300 Mariupol residents to Nakhodka, a port town in Siberia, on the coast of Pacific Ocean. No way those people would have money to return to Ukraine from that far. This is madness. Austrian, German governments are you fine?',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/77.jpg',
      },
      {
        Tokenid: '437',
        DayNo: '59',
        FullDate: '4/23/2022',
        Time: '19:07',
        TwitterUrl: 'https://twitter.com/the_ins_ru/status/1517897961912651777',
        TwitterUsername: 'the_ins_ru',
        Headline:
          'The Telegraph: 10 стран ЕС продали России оружие на 350 млн евро в обход эмбарго',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/78.jpg',
      },
      {
        Tokenid: '438',
        DayNo: '59',
        FullDate: '4/23/2022',
        Time: '20:54',
        TwitterUrl: 'https://twitter.com/dw_russian/status/1517924915982356480',
        TwitterUsername: 'dw_russian',
        Headline:
          'Зеленский - об обстреле Одессы военными РФ: "В жилой многоэтажный дом попала ракета. Восемь человек погибли. Ребенка убили трехмесячного. Подонки вонючие. Других нет слов". Президент Украины дает большую пресс-конференцию в киевском метро',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/79.jpg',
      },
      {
        Tokenid: '439',
        DayNo: '59',
        FullDate: '4/23/2022',
        Time: '21:10',
        TwitterUrl:
          'https://twitter.com/olliecarroll/status/1517928932535934979',
        TwitterUsername: 'olliecarroll',
        Headline:
          'Zelensky in message to Moscow: “Life in Russia is virtual reality… You should return to the real, civilised world! It’s wonderful. Truth is wonderful.”',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/80.jpg',
      },
      {
        Tokenid: '440',
        DayNo: '59',
        FullDate: '4/23/2022',
        Time: '21:17',
        TwitterUrl:
          'https://twitter.com/Gerashchenko_en/status/1517930674304565248',
        TwitterUsername: 'Gerashchenko_en',
        Headline:
          "Tetiana Kushnir, doctor with the National Guards of Ukraine, died in #Mariupol #Azovstal. 40 days ago her husband was killed. They have a baby son left (he's safe). Rest in peace, Tetiana. We will avenge you. #ArmUkraineNow",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/81.jpg',
      },
    ],
  },
  {
    dayNo: 60,
    date: '24 Apr 2022',
    events: [
      {
        Tokenid: '441',
        DayNo: '60',
        FullDate: '4/24/2022',
        Time: '02:32',
        TwitterUrl: 'https://twitter.com/visegrad24/status/1518010043311996928',
        TwitterUsername: 'visegrad24',
        Headline:
          'BREAKING: Without making it public, Slovakia has started transferring T-72 tanks to Ukraine. Two of them were spotted today in the Luhansk region, heading for the frontlines. Great job Slovakia! 🇸🇰🇺🇦',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/82.jpg',
      },
      {
        Tokenid: '442',
        DayNo: '60',
        FullDate: '4/24/2022',
        Time: '21:11',
        TwitterUrl: 'https://twitter.com/POTUS/status/1518291602975989762',
        TwitterUsername: 'POTUS',
        Headline:
          'Two months after Putin launched an unprovoked and unjustified attack on Ukraine, Kyiv still stands. President Zelenskyy and his democratically-elected government remain in power. We will continue to support Ukrainians in their fight to defend their homeland.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/83.jpg',
      },
    ],
  },
  {
    dayNo: 61,
    date: '25 Apr 2022',
    events: [
      {
        Tokenid: '443',
        DayNo: '61',
        FullDate: '4/25/2022',
        Time: '02:15',
        TwitterUrl: 'https://twitter.com/mtracey/status/1518368149267267585',
        TwitterUsername: 'mtracey',
        Headline:
          "The head of the Pentagon is physically in Ukraine right now, just in case you were wondering about the trajectory of the US military's involvement in the war",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/84.jpg',
      },
      {
        Tokenid: '444',
        DayNo: '61',
        FullDate: '4/25/2022',
        Time: '22:50',
        TwitterUrl:
          'https://twitter.com/StephenKing/status/1518346671255703566',
        TwitterUsername: 'StephenKing',
        Headline: 'Macron’s victory is another stinging defeat for Putin.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/85.jpg',
      },
    ],
  },
  {
    dayNo: 62,
    date: '26 Apr 2022',
    events: [
      {
        Tokenid: '445',
        DayNo: '62',
        FullDate: '4/26/2022',
        Time: '00:08',
        TwitterUrl:
          'https://twitter.com/DmytroKuleba/status/1518698466758864898',
        TwitterUsername: 'DmytroKuleba',
        Headline:
          'Russia loses last hope to scare the world off supporting Ukraine. Thus the talk of a ‘real’ danger of WWIII. This only means Moscow senses defeat in Ukraine. Therefore, the world must double down on supporting Ukraine so that we prevail and safeguard European and global security.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/86.jpg',
      },
      {
        Tokenid: '446',
        DayNo: '62',
        FullDate: '4/26/2022',
        Time: '19:02',
        TwitterUrl:
          'https://twitter.com/ZuzanaCaputova/status/1518983948310827009',
        TwitterUsername: 'ZuzanaCaputova',
        Headline:
          'With its invasion of #Ukraine, #Russia has brought suffering & pain as the number of victims of sexual violence continues to grow. No war is a justification for such crimes. I appeal to Russia’s soldiers & their superiors to put an end to their violence.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/87.jpg',
      },
      {
        Tokenid: '447',
        DayNo: '62',
        FullDate: '4/26/2022',
        Time: '20:40',
        TwitterUrl: 'https://twitter.com/Klitschko/status/1519008421500043266',
        TwitterUsername: 'Klitschko',
        Headline:
          "You don't kill your brother. You don't rape your sister. You don't destroy your friend's country. That's why today we dismantled this monument once created as a sign of friendship between Ukraine and Russia. #FreeUkraine #WeAreAllUkrainians #StandWithUkraine #StopTheWar",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/88.jpg',
      },
      {
        Tokenid: '448',
        DayNo: '62',
        FullDate: '4/26/2022',
        Time: '22:42',
        TwitterUrl: 'https://twitter.com/dw_russian/status/1519039177811275779',
        TwitterUsername: 'dw_russian',
        Headline:
          'Министры обороны более 40 стран, в том числе не состоящих в НАТО, завершили встречу на базе ВВС США в Рамштайне, договорившись о создании коалиции в поддержку Украины. Глава Пентагона Ллойд Остин назвал встречу "исторической"',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/89.jpg',
      },
      {
        Tokenid: '449',
        DayNo: '62',
        FullDate: '4/26/2022',
        Time: '23:25',
        TwitterUrl: 'https://twitter.com/McFaul/status/1519050002147860481',
        TwitterUsername: 'McFaul',
        Headline:
          'People sometimes forget embassies have major military representation stationed at them. Reopening our embassy in Kyiv will enhance dramatically mil-to-mil cooperation between Ukraine and the United States.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/90.jpg',
      },
    ],
  },
  {
    dayNo: 63,
    date: '27 Apr 2022',
    events: [
      {
        Tokenid: '450',
        DayNo: '63',
        FullDate: '4/27/2022',
        Time: '17:15',
        TwitterUrl:
          'https://twitter.com/DmytroKuleba/status/1519319368148082689',
        TwitterUsername: 'DmytroKuleba',
        Headline:
          'Russia has been suspended from @UNWTO at its General Assembly’s first extraordinary session. Grateful to all members who backed this move. The only travel direction for Russian war criminals should be The Hague. Russia’s isolation will deepen with each day of its war on Ukraine.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/91.jpg',
      },
      {
        Tokenid: '451',
        DayNo: '63',
        FullDate: '4/27/2022',
        Time: '22:56',
        TwitterUrl:
          'https://twitter.com/olgatokariuk/status/1519405188779499527',
        TwitterUsername: 'olgatokariuk',
        Headline:
          "In the occupied Kherson region, Russians have created a prison camp on the territory of a pre-trial detention center where 300 Ukrainian activists and war veterans are being held. According to Ukraine's defense intelligence, people are interrogated, beaten and tortured there",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/92.jpg',
      },
    ],
  },
  {
    dayNo: 64,
    date: '28 Apr 2022',
    events: [
      {
        Tokenid: '452',
        DayNo: '64',
        FullDate: '4/28/2022',
        Time: '00:39',
        TwitterUrl:
          'https://twitter.com/KyivIndependent/status/1519446116865085441',
        TwitterUsername: 'KyivIndependent',
        Headline:
          '⚡️Canada lawmakers vote to label Russia’s acts in Ukraine as ‘genocide.’ Canadian lawmakers voted unanimously on April 27 to call Russia’s attacks in Ukraine a “genocide”, adding that there was “ample evidence of systemic and massive war crimes against humanity.”',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/93.jpg',
      },
      {
        Tokenid: '453',
        DayNo: '64',
        FullDate: '4/28/2022',
        Time: '20:37',
        TwitterUrl: 'https://twitter.com/POTUS/status/1519732444299153412',
        TwitterUsername: 'PotUS',
        Headline:
          'Despite the disturbing rhetoric coming out of the Kremlin, the facts are plain for all to see: We are not attacking Russia. We are helping Ukraine defend itself against Russian aggression. And just as Putin chose to launch this brutal invasion, he could make the choice to end it.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/94.jpg',
      },
      {
        Tokenid: '454',
        DayNo: '64',
        FullDate: '4/28/2022',
        Time: '20:58',
        TwitterUrl:
          'https://twitter.com/DmytroKuleba/status/1519737764127940610',
        TwitterUsername: 'DmytroKuleba',
        Headline:
          'Russia stroke Kyiv with cruise missiles right when UN Secretary General @antonioguterres and Bulgarian PM @KirilPetkov visit our capital. By this heinous act of barbarism Russia demonstrates once again its attitude towards Ukraine, Europe and the world.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/95.jpg',
      },
    ],
  },
  {
    dayNo: 65,
    date: '29 Apr 2022',
    events: [
      {
        Tokenid: '455',
        DayNo: '65',
        FullDate: '4/29/2022',
        Time: '00:49',
        TwitterUrl: 'https://twitter.com/tribelaw/status/1519796071169466369',
        TwitterUsername: 'tribelaw',
        Headline:
          'Pardon me for asking, but why the F doesn’t the UN just expel Russia? It’s now a terrorist state, not a “nation” worthy of the name.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/96.jpg',
      },
      {
        Tokenid: '456',
        DayNo: '65',
        FullDate: '4/29/2022',
        Time: '20:54',
        TwitterUrl: 'https://twitter.com/McFaul/status/1520099220568518656',
        TwitterUsername: 'McFaul',
        Headline:
          'НАТО никогда не нападала на СССР или Россию и не будет этого делать никогда, если только Путин не нападет на НАТО первым.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/97.jpg',
      },
      {
        Tokenid: '457',
        DayNo: '65',
        FullDate: '4/29/2022',
        Time: '21:55',
        TwitterUrl: 'https://twitter.com/SecDef/status/1520114633218080774',
        TwitterUsername: 'SecDef',
        Headline:
          "Ukraine's hospitals have been bombed. Their citizens have been executed. Their children have been traumatized. And yet, despite all that, they have done a magnificent job defending their sovereignty. Ukraine’s valor and skill will go down in military history.",
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/98.jpg',
      },
    ],
  },
  {
    dayNo: 66,
    date: '30 Apr 2022',
    events: [
      {
        Tokenid: '458',
        DayNo: '66',
        FullDate: '4/30/2022',
        Time: '00:37',
        TwitterUrl:
          'https://twitter.com/MikhailFishman/status/1520155265794027526',
        TwitterUsername: 'MikhailFishman',
        Headline:
          'Парадокс истории: чем дольше Россия воюет с Украиной, захватывает ее регионы, уничтожает и разрушает ее города, тем очевиднее, что у Украины есть будущее, а у России – нет.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/99.jpg',
      },
      {
        Tokenid: '459',
        DayNo: '66',
        FullDate: '4/30/2022',
        Time: '22:19',
        TwitterUrl:
          'https://twitter.com/KyivIndependent/status/1520483058453037059',
        TwitterUsername: 'KyivIndependent',
        Headline:
          '⚡️Mariupol mayor: Russian military killed twice as many residents as Nazi Germany. Vadym Boychenko said that in 2 years of Mariupol’s occupation during World War II, the Nazis killed 10,000 people. Russians have doubled the number of victims in 2 months of the Mariupol siege.',
        DescriptionEnglish: '',
        DescriptionUkrainian: '',
        ArtistName: 'Sirens Gallery',
        ArtistLink: 'https://sirens.gallery/',
        ImageType: 'drop4/100.jpg',
      },
    ],
  },
].map((day) => ({
  ...day,
  events: day.events.map((event) => ({
    ...event,
    Editions: 8,
    WarlineDrop: WarlineDrop.Drop4,
    IsWhitelisted: true,
  })),
})) as ReadonlyArray<DayType>;
