import { DayType } from "@sections/types";

const WarlineData: Array<DayType> = [
  {
    "dayNo":1,
    "date":"24 Feb 2022",
    "events":[
      {
        "Tokenid":"1",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"05:45",
        "TwitterUrl":"https://twitter.com/BBCNews/status/1496692738024161282",
        "TwitterUsername":"BBCNews",
        "Headline":"Ukraine conflict: Russia announces special military operation in Donbas",
        "DescriptionEnglish":"Russian forces have launched a major assault on Ukraine, firing missiles on cities and military targets.\nThe invasion by land, air and sea began after a pre-dawn TV address where Russian President Vladimir Putin demanded that Ukraine's military lay down its arms.",
        "DescriptionUkrainian":"Російські війська розпочали масштабний наступ на Україну, обстрілюючи міста та військові об'єкти.\nВторгнення на суші, повітрі та морі почалося після передсвітанкового телезвернення, де президент Росії Володимир Путін вимагав від українських військових скласти зброю.",
        "ArtistName":"Yaroslav DRZK",
        "ArtistLink":"https://instagram.com/drzk_artist?utm_medium=copy_link",
        "ImageType":"1.gif"
      },
      {
        "Tokenid":"2",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"05:58",
        "TwitterUrl":"https://twitter.com/DmytroKuleba/status/1496695889401896964?cxt=HHwWiICziem-qsUpAAAA",
        "TwitterUsername":"DmytroKuleba",
        "Headline":"Putin has just launched a full-scale invasion of Ukraine. Peaceful Ukrainian cities are under strikes. This is a war of aggression. Ukraine will defend itself and will win. The world can and must stop Putin. The time to act is now.",
        "DescriptionEnglish":"Russia's invasion of Ukraine, the shelling of civilian and military targets, are the best ways to act and support Ukraine. Together we will stop Putin and win!",
        "DescriptionUkrainian":"Російське вторгнення в Україну, обстріл цивільних та військових об'єктів - кращий спосіб почати діяти і підтримати Україну. Разом ми зупинемо Путіна і переможемо!",
        "ArtistName":"Ivan Ponomarchuk",
        "ArtistLink":"https://www.behance.net/cordduro",
        "ImageType":"2.jpg"
      },
      {
        "Tokenid":"3",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"06:58",
        "TwitterUrl":"https://twitter.com/DmytroKuleba/status/1496711163530424324",
        "TwitterUsername":"DmytroKuleba",
        "Headline":"The world must act immediately. Future of Europe & the world is at stake. To do list:\n\n1. Devastating sanctions on Russia NOW, including SWIFT\n2. Fully isolate Russia by all means, in all formats\n3. Weapons, equipment for Ukraine\n4. Financial assistance\n5. Humanitarian assistance",
        "DescriptionEnglish":"Ukrainian Foreign Minister Dmytro Kuleba called on the whole world to take five steps to stop Putin.",
        "DescriptionUkrainian":"Міністр закордонних справ України Дмитро Кулеба закликав увесь світ зробити 5 важливих кроків, щоб зупинити Путіна.",
        "ArtistName":"Oleksii Pryshchepa",
        "ArtistLink":"https://instagram.com/o.pryshchepa_?utm_medium=copy_link",
        "ImageType":"3.png"
      },
      {
        "Tokenid":"4",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"07:02",
        "TwitterUrl":"https://twitter.com/DefenceU/status/1496712173250387968",
        "TwitterUsername":"DefenceU",
        "Headline":"Speech by President of Ukraine Volodymyr Zelenskyy",
        "DescriptionEnglish":"Volodymyr Zelenskyy in connection with the people of Ukraine: \"We are Ukraine! Glory to Ukraine!\"",
        "DescriptionUkrainian":"Володимир Зеленський на зв'язку з народом України: \"Ми - це Україна! Слава Україні!\"",
        "ArtistName":"Kvi Kvi",
        "ArtistLink":"https://instagram.com/kvikvi.design?utm_medium=copy_link",
        "ImageType":"4.png"
      },
      {
        "Tokenid":"5",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"07:33",
        "TwitterUrl":"https://twitter.com/DPSU_ua/status/1496719970780254209",
        "TwitterUsername":"DPSU_ua",
        "Headline":"The state border of Ukraine was attacked by Russian troops from Russia and Belarus",
        "DescriptionEnglish":"The State Border Guard Service of Ukraine reported an attack on the border not only from the Russian Federation, but also from Belarus.",
        "DescriptionUkrainian":"Державний кордон України піддався атаці російських військ з боку Російської Федерації та Республіки Білорусь",
        "ArtistName":"Sheverev Dmytro",
        "ArtistLink":"https://instagram.com/shesvit?utm_medium=copy_link",
        "ImageType":"5.gif"
      },
      {
        "Tokenid":"6",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"08:08",
        "TwitterUrl":"https://twitter.com/vonderleyen/status/1496728814013067269?s=20&t=85OH7cBfmEDep68HEae3ig",
        "TwitterUsername":"vonderleyen",
        "Headline":"We condemn Russia’s unprecedented military aggression against Ukraine.\n\nIt must withdraw its military and fully respect Ukraine's territorial integrity.\n \nThe EU leaders will discuss and swiftly adopt further restrictive measures against Russia.\n\nThe EU stands with Ukraine.",
        "DescriptionEnglish":"Statement by Ursula von der Leyen and President Charles Michel",
        "DescriptionUkrainian":"Заява Урсули фон дер Ляйєн і президента Шарля Мішеля",
        "ArtistName":"Tina Tykhonenko",
        "ArtistLink":"https://instagram.com/tihotak?utm_medium=copy_link",
        "ImageType":"6.jpg"
      },
      {
        "Tokenid":"7",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"09:07",
        "TwitterUrl":"https://twitter.com/APUkraine/status/1496743488133734400",
        "TwitterUsername":"APUkraine",
        "Headline":"President Volodymyr Zelensky signed Decree № 64/2022 \"On the imposition of martial law in Ukraine.\" Deputies approved the document by 300 votes.",
        "DescriptionEnglish":"The President signed a decree on the imposition of martial law in Ukraine, and the Verkhovna Rada approved it",
        "DescriptionUkrainian":"Президент підписав указ про запровадження воєнного стану в Україні, Верховна Рада його затвердила",
        "ArtistName":"Serj Marco aka marcovector",
        "ArtistLink":"https://www.behance.net/marcovector",
        "ImageType":"7.jpg"
      },
      {
        "Tokenid":"8",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"09:24",
        "TwitterUrl":"https://twitter.com/APUkraine/status/1496747915854987266",
        "TwitterUsername":"APUkraine",
        "Headline":"In accordance with the launch of a military operation against Ukraine by Russia, President Volodymyr Zelensky held an urgent meeting with the leadership of the government, representatives of the defense sector and the economic bloc.",
        "DescriptionEnglish":"The head of state held an urgent meeting in connection with Russia's launch of a military operation against Ukraine",
        "DescriptionUkrainian":"Глава держави провів термінову нараду у зв’язку з початком Росією військової операції проти України",
        "ArtistName":"Anna Voda",
        "ArtistLink":"https://www.instagram.com/anna.voda/",
        "ImageType":"8.jpg"
      },
      {
        "Tokenid":"9",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"10:11",
        "TwitterUrl":"https://twitter.com/RFERL/status/1496759659356639232",
        "TwitterUsername":"RFERL",
        "Headline":"Footage from this morning shows a Russian cruise missile hitting the airport of Ivano-Frankivsk, in western Ukraine, as well as strikes on other cities.",
        "DescriptionEnglish":"Russia launched rocket attacks on Ukrainian cities. The missile had hit airport of Ivano-Frankivsk",
        "DescriptionUkrainian":"Росія завдала ракетних ударів по українських містах.",
        "ArtistName":"IlonaDesignArt",
        "ArtistLink":"https://www.instagram.com/ilona_design/",
        "ImageType":"9.jpg"
      },
      {
        "Tokenid":"10",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"11:43",
        "TwitterUrl":"https://twitter.com/BBC_ua/status/1496782837739311105?s=20&t=HkyvIkVIBRe-2fHE50tgmA",
        "TwitterUsername":"BBC_ua",
        "Headline":"Ukraine under attack: Russia attacked airports, bases, warehouses",
        "DescriptionEnglish":"Eyewitnesses from all over Ukraine report shelling of key infrastructure by Russia.\nAirports, military units and warehouses - all this came under rocket fire.",
        "DescriptionUkrainian":"Очевидці з усієї України повідомляють про обстріли Росією ключових об'єктів інфраструктури.\nЛетовища, військові частини і склади - все це опинилося під ракетними обстрілами.",
        "ArtistName":"Ira Chuzh",
        "ArtistLink":"https://instagram.com/nalune.art",
        "ImageType":"10.jpg"
      },
      {
        "Tokenid":"11",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"11:50",
        "TwitterUrl":"https://twitter.com/BorisJohnson/status/1496784638584360961?s=20&t=lCpYM0Lsn_6iNaaXDNFgjQ",
        "TwitterUsername":"BorisJohnson",
        "Headline":"This is a catastrophe for our continent. \n\nI will make an address to the nation this morning on the Russian invasion of Ukraine. \n\nI will also speak to fellow G7 leaders and I am calling for an urgent meeting of all NATO leaders as soon as possible.",
        "DescriptionEnglish":"Boris Johnson convenes an emergency NATO summit.",
        "DescriptionUkrainian":"Борис Джонсон скликає екстренний саміт НАТО.",
        "ArtistName":"Iryna Vale",
        "ArtistLink":"https://www.instagram.com/vale.illustration/ ",
        "ImageType":"11.jpg"
      },
      {
        "Tokenid":"12",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"11:55",
        "TwitterUrl":"https://twitter.com/ZelenskyyUa/status/1496785776486584320",
        "TwitterUsername":"ZelenskyyUa",
        "Headline":"We have severed diplomatic relations with Russia. For all those who have not yet lost their conscience in Russia, it is time to go out and protest against the war with Ukraine.",
        "DescriptionEnglish":"Ukraine severed diplomatic relations with Russia - President of Ukraine",
        "DescriptionUkrainian":"Україна розірвала дипломатичні відносини з Росією",
        "ArtistName":"Albert Nikogosyan",
        "ArtistLink":"https://instagram.com/n1kogosyan?utm_medium=copy_link ",
        "ImageType":"12.jpg"
      },
      {
        "Tokenid":"13",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"12:26",
        "TwitterUrl":"https://twitter.com/GeneralStaffUA/status/1496974776438509572?s=20&t=p5irU04p0kshVrvWUGUcaA",
        "TwitterUsername":"GeneralStaffUA",
        "Headline":"DECREE OF THE PRESIDENT OF UKRAINE № 69/2022\nAbout the general mobilization",
        "DescriptionEnglish":"President Zelensky submitted a draft law on general mobilization to the Rada.",
        "DescriptionUkrainian":"Президент Зеленський вніс до Ради проект закону про загальну мобілізацію.",
        "ArtistName":"Bezkorovainyi Oleksii aka eviltorn",
        "ArtistLink":"https://instagram.com/eviltornsberg",
        "ImageType":"13.png"
      },
      {
        "Tokenid":"14",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"15:06",
        "TwitterUrl":"https://twitter.com/DmytroKuleba/status/1496833857009729547?s=20&t=ecB_Iz7Q_2aVN6gle6PZSg",
        "TwitterUsername":"DmytroKuleba",
        "Headline":"Ukraine has severed diplomatic relations with Russia. I call on all our partners to do the same. By this concrete step you will demonstrate that you stand by Ukraine and categorically reject the most blatant act of aggression in Europe since WWII.",
        "DescriptionEnglish":"Ukrainian Foreign Minister Kuleba called on all partners of the country to break off diplomatic relations with Russia",
        "DescriptionUkrainian":"Міністр закордонних справ України Кулеба закликав усіх партнерів країни розірвати дипломатичні відносини з Росією",
        "ArtistName":"IlonaDesignArt",
        "ArtistLink":"https://www.instagram.com/ilona_design/",
        "ImageType":"14.jpg"
      },
      {
        "Tokenid":"15",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"15:36",
        "TwitterUrl":"https://twitter.com/ZelenskyyUa/status/1496841445822668801 ",
        "TwitterUsername":"ZelenskyyUa",
        "Headline":"We are creating an anti-Putin coalition. I spoke with @vonderleyen, @EmmanuelMacron, @karlnehammer and @RTErdogan about concrete sanctions and concrete assistance for our military. We are waiting for decisive action.",
        "DescriptionEnglish":"We are creating an anti-Putin coalition.",
        "DescriptionUkrainian":"Ми створюємо антипутінську коаліцію.",
        "ArtistName":"Orome",
        "ArtistLink":"https://www.instagram.com/romankupriyan/",
        "ImageType":"15.png"
      },
      {
        "Tokenid":"16",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"16:04",
        "TwitterUrl":"https://twitter.com/WhiteHouse/status/1496848568052813827?s=20&t=v90d0wjll2QI4vobBbGD8g",
        "TwitterUsername":"WhiteHouse",
        "Headline":"President Biden met with his national security team in the Situation Room this morning to discuss the latest developments in Ukraine. He discussed how we will hold Russia accountable for its unprovoked and unjustified attack on Ukraine.",
        "DescriptionEnglish":"Discussion of national security team and US president Biden about the situation in Ukraine",
        "DescriptionUkrainian":"Президент Байден сьогодні вранці зустрівся зі своєю командою національної безпеки в Ситуаційній кімнаті, щоб обговорити останні події в Україні.",
        "ArtistName":"amarynoff",
        "ArtistLink":"https://www.instagram.com/amarynoff/",
        "ImageType":"16.jpg"
      },
      {
        "Tokenid":"17",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"16:19",
        "TwitterUrl":"https://twitter.com/MFA_Ukraine/status/1496852201456775177?s=20&t=1vkP1Mkd5zcMbkDTxFu88w",
        "TwitterUsername":"MFA_Ukraine",
        "Headline":"From the territory of the Republic of Belarus 4 ballistic missiles were launched towards Southwestern direction.",
        "DescriptionEnglish":"Ukrainian land was attacked by the ballistic missiles from the territory of Republic Belarus",
        "DescriptionUkrainian":"З території Республіки Білорусь було запущено 4 балістичні ракети в південно-західному напрямку.",
        "ArtistName":"Orome",
        "ArtistLink":"https://www.instagram.com/romankupriyan/",
        "ImageType":"17.png"
      },
      {
        "Tokenid":"18",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"16:21",
        "TwitterUrl":"https://twitter.com/DPSU_ua/status/1496852701380063240",
        "TwitterUsername":"DPSU_ua",
        "Headline":"Snake Island was attacked by Russian military ships",
        "DescriptionEnglish":"Ukrainian Snake Island located in the Black Sea was attacked by Russian military ships",
        "DescriptionUkrainian":"Острів Зміїний атаковано російськими військовими кораблями",
        "ArtistName":"IlonaDesignArt",
        "ArtistLink":"https://www.instagram.com/ilona_design/",
        "ImageType":"18.jpg"
      },
      {
        "Tokenid":"19",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"16:57",
        "TwitterUrl":"https://twitter.com/GeneralStaffUA/status/1496861861714739200",
        "TwitterUsername":"GeneralStaffUA",
        "Headline":"On February 24, according to the Joint Forces Command, in the Hlukhov area, the military used Javelin anti-aircraft missiles and neutralized a column of russian vehicles - 15 T-72 tanks",
        "DescriptionEnglish":"The military used Javelin anti-aircraft missiles and neutralized a column of russian vehicles - 15 T-72 tanks.",
        "DescriptionUkrainian":"Військові застосували зенітні ракети Javelin та знешкодили колону російської техніки – 15 танків Т-72.",
        "ArtistName":"Alina Kropachova",
        "ArtistLink":"https://www.behance.net/AlinaKro\n",
        "ImageType":"19.jpg"
      },
      {
        "Tokenid":"20",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"17:00",
        "TwitterUrl":"https://twitter.com/ZelenskyyUa/status/1496862540957114370",
        "TwitterUsername":"ZelenskyyUa",
        "Headline":"Russian occupation forces are trying to seize the #Chornobyl_NPP. Our defenders are giving their lives so that the tragedy of 1986 will not be repeated. Reported this to \n@SwedishPM. This is a declaration of war against the whole of Europe.",
        "DescriptionEnglish":"Russian occupation forces are trying pass through the Chornobyl zone",
        "DescriptionUkrainian":"Російсько-окупаційні війська намагаються пройти через Чорнобильську зону",
        "ArtistName":"Mark Bushuiev",
        "ArtistLink":"https://instagram.com/mark_scalpit?utm_medium=copy_link",
        "ImageType":"20.jpg"
      },
      {
        "Tokenid":"21",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"17:59",
        "TwitterUrl":"https://twitter.com/ZelenskyyUa/status/1496877445332582407",
        "TwitterUsername":"ZelenskyyUa",
        "Headline":"A package of additional tough sanctions against Russia from the EU is approaching. Discussed all the details with  @EmmanuelMacron. We demand the disconnection of Russia from SWIFT, the introduction of a no-fly zone over Ukraine and other effective steps to stop the aggressor.",
        "DescriptionEnglish":"A package of additional tough sanctions against the Russian Federation from the EU is already on the way",
        "DescriptionUkrainian":"Пакет додаткових жорстких санкцій проти Російської Федерації з боку ЄС уже на шляху",
        "ArtistName":"Daria Borodenko",
        "ArtistLink":"https://www.instagram.com/_da_riiia_/",
        "ImageType":"21.png"
      },
      {
        "Tokenid":"22",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"22:10",
        "TwitterUrl":"https://twitter.com/FCDOGovUK/status/1496940691750019080",
        "TwitterUsername":"FCDOGovUK",
        "Headline":"The UK will also:\n❌ ban Aeroflot from UK airspace\n❌ cut off wealthy Russians’ access to UK banks including limits on investments\n❌ work with allies to ban Russia from the SWIFT financial system",
        "DescriptionEnglish":"The UK will support sanctions against Russia, including ban of Aeroflot, ban of SWIFT and limitations on investments",
        "DescriptionUkrainian":"Велика Британія підтримає санкції проти Росії",
        "ArtistName":"Orome",
        "ArtistLink":"https://www.instagram.com/romankupriyan/",
        "ImageType":"22.png"
      },
      {
        "Tokenid":"23",
        "DayNo":"1",
        "FullDate":"2/24/2022",
        "Time":"23:27",
        "TwitterUrl":"https://twitter.com/SkyNews/status/1496960058026037251?s=20&t=2eQrO7a5B4BscLm7OEwOtA",
        "TwitterUsername":"SkyNews",
        "Headline":"UEFA is to announce tomorrow it is moving the Champions League final from St Petersburg, following Russia's invasion of Ukraine.",
        "DescriptionEnglish":"UEFA is moving the planned Champions League final from St Petersburg",
        "DescriptionUkrainian":"УЄФА переносить фінал Ліги чемпіонів із Санкт-Петербурга",
        "ArtistName":"Sveta Bilyk",
        "ArtistLink":"https://svetabilyk.com/",
        "ImageType":"23.jpg"
      }
    ]
  },
  {
    "dayNo":2,
    "date":"25 Feb 2022",
    "events":[
      {
        "Tokenid":"24",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"03:33",
        "TwitterUrl":"https://twitter.com/vonderleyen/status/1497021840572796928?s=20&t=yXtDFP3n2Ft6BeNoRRlkcA",
        "TwitterUsername":"vonderleyen",
        "Headline":"The package of massive and targeted sanctions approved tonight shows how united the EU is. \n\nFirst, this package includes financial sanctions, targeting 70% of the Russian banking market and key state owned companies, including in defence.",
        "DescriptionEnglish":"Press conference following the European Council to support Ukraine",
        "DescriptionUkrainian":"Прес-конференція за підсумками засідання Європейської Ради на підтримку України",
        "ArtistName":"Casekimba",
        "ArtistLink":"https://hicetnunc.art/casekimba",
        "ImageType":"24.png"
      },
      {
        "Tokenid":"25",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"05:30",
        "TwitterUrl":"https://twitter.com/WSJ/status/1497051255444852736",
        "TwitterUsername":"WSJ",
        "Headline":"Roughly 100,000 Ukrainians have been displaced, according to estimates from the United Nations High Commissioner for Refugees",
        "DescriptionEnglish":"As a result of the war, about 100 thousand Ukrainians had to leave their homes",
        "DescriptionUkrainian":"",
        "ArtistName":"ira dja ",
        "ArtistLink":"https://www.behance.net/iradja ",
        "ImageType":"25.jpg"
      },
      {
        "Tokenid":"26",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"05:50",
        "TwitterUrl":"https://twitter.com/Kabmin_UA_e/status/1497056378438959114",
        "TwitterUsername":"Kabmin_UA_e",
        "Headline":"#RussianInvasion State Border Guard Service informs at 4.25 enemy attacked border guard unit in Zaporizhia region by rockets. As a result of attack there are casualties.\n#Ukraine #Kabmin #Emergency #Defense #StopRussianAggression",
        "DescriptionEnglish":"As a result of rocket attack on Zaporizhia region, there are several casualties",
        "DescriptionUkrainian":"Держприкордонслужба повідомляє, що о 4.25 противник обстріляв прикордонний підрозділ у Запорізькій області. В результаті обстрілу є постраждалі.",
        "ArtistName":"Sheverev Dmytro",
        "ArtistLink":"https://instagram.com/shesvit?utm_medium=copy_link",
        "ImageType":"26.jpg"
      },
      {
        "Tokenid":"27",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"05:57",
        "TwitterUrl":"https://twitter.com/DmytroKuleba/status/1497058048430460934",
        "TwitterUsername":"DmytroKuleba",
        "Headline":"Horrific Russian rocket strikes on Kyiv. Last time our capital experienced anything like this was in 1941 when it was attacked by Nazi Germany. Ukraine defeated that evil and will defeat this one. Stop Putin. Isolate Russia. Severe all ties. Kick Russia out of everywhete.",
        "DescriptionEnglish":"Russian rocket strikes on Kyiv. \"Last time our capital experienced anything like this was in 1941 when it was attacked by Nazi Germany.\" said Minister of Foreign Affairs of Ukraine",
        "DescriptionUkrainian":"Російські ракетні удари по Києву. \"Востаннє наша столиця переживала щось подібне в 1941 році, коли на неї напала нацистська Німеччина.\"",
        "ArtistName":"Alisa Gots ",
        "ArtistLink":"https://instagram.com/alisa.gots?utm_medium=copy_link ",
        "ImageType":"27.jpg"
      },
      {
        "Tokenid":"28",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"09:54",
        "TwitterUrl":"https://twitter.com/ZelenskyyUa/status/1497117756734464022",
        "TwitterUsername":"ZelenskyyUa",
        "Headline":"Held talks with PM @BorisJohnson. Reported on the course of Ukraine defense and insidious attacks on Kyiv by the aggressor. Today Ukraine needs the support of partners more than ever. We demand effective counteraction to the Russian Federation. Sanctions must be further strengthened.",
        "DescriptionEnglish":"Ukrainian President Zelenskyy had reported about the current situation in Ukraine during the talk with Boris Johnson",
        "DescriptionUkrainian":"Провів переговори з PM @BorisJohnson. Повідомляється про хід оборони України та підступні напади агресора на Київ.",
        "ArtistName":"Hordiy Vasylash",
        "ArtistLink":"https://hordiyvasylash.com/ ",
        "ImageType":"28.jpg"
      },
      {
        "Tokenid":"29",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"10:37",
        "TwitterUrl":"https://twitter.com/ZelenskyyUa/status/1497128614676123648",
        "TwitterUsername":"ZelenskyyUa",
        "Headline":"Discussed with @niinisto countering the aggressor. Informed about our defense, insidious shelling of Kyiv. Grateful to Finland for allocating $50 million aid. It’s an effective contribution to the anti-war coalition. We keep working. We need to increase sanctions & Ukraine defense support ",
        "DescriptionEnglish":"Zelensky Discussed with President of Finland countering the aggressor Grateful to Finland for allocating $50 million aid",
        "DescriptionUkrainian":"Зеленський обговорив з президентом Фінляндії протидію агресору Вдячний Фінляндії за виділення $50 млн допомоги",
        "ArtistName":"Julie Grechukh",
        "ArtistLink":"https://www.behance.net/juliegrechb30e",
        "ImageType":"29.jpg"
      },
      {
        "Tokenid":"30",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"14:15",
        "TwitterUrl":"https://twitter.com/RFERL/status/1497183566051954693",
        "TwitterUsername":"RFERL",
        "Headline":"The Russian foreign minister said that Moscow will hold talks with Ukraine only after Kyiv stops its military resistance to the Russian Army.",
        "DescriptionEnglish":"Russian Foreign Minister Sergei Lavrov has said that Ukrainian President Volodymyr Zelenskiy \"lost all chances\" to discuss regional security with Moscow as Russian troops continued military operations against Ukrainian towns and cities.\nLavrov also said that 'nobody plans to occupy Ukraine,\" reiterating President Vladimir Putin's claim that the goal of ongoing military invasion of Ukraine was the \"demilitarization and de-Nazification\" of Ukraine.",
        "DescriptionUkrainian":"Лавров заявив, що Київ втратив шанс обговорити регіональну безпеку через продовження нападу Росії на Україну",
        "ArtistName":"Serhii Holtvianskyi",
        "ArtistLink":"https://www.instagram.com/ser.golt/",
        "ImageType":"30.png"
      },
      {
        "Tokenid":"31",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"15:16",
        "TwitterUrl":"https://twitter.com/ArmedForcesUkr/status/1497198793196023809",
        "TwitterUsername":"ArmedForcesUkr",
        "Headline":"Do not believe the aggressor that he strikes ONLY on military infrastructure \n\n The cynical lie of the Russian Federation is refuted by the head of the Sumy regional military administration Dmitry Zhyvytsky.\n The fact of shelling by \"hurricanes\" in Okhtyrka which got to a housing estate, bomb shelters, kindergarten is fixed.",
        "DescriptionEnglish":"The fact of shelling by \"hurricanes\" in Okhtyrka which got to a housing estate, bomb shelters, kindergarten is fixed.",
        "DescriptionUkrainian":"Зафіксовано факт обстрілу «ураганами» в Охтирці, які потрапили у житловий масив, бомбосховища, дитячий садок.",
        "ArtistName":"Viktoriia Gets",
        "ArtistLink":"https://www.behance.net/viktoriiagets",
        "ImageType":"31.jpg"
      },
      {
        "Tokenid":"32",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"16:23",
        "TwitterUrl":"https://twitter.com/MVS_UA/status/1497215676246859776",
        "TwitterUsername":"MVS_UA",
        "Headline":"At 13:15 in the village. A cruise missile hit Radchytsia in the Korosten district, as a result of which the structure of the elevator was damaged, followed by burning. Sunflower seeds were planted on an area of 20 sq.m. SES officers put out the fire at 3:07 p.m. No one was killed or injured.",
        "DescriptionEnglish":"A cruise missile hit the elevator in the Korosten district. The seeds were burning, but no casualties reported",
        "DescriptionUkrainian":"Крилата ракета влучила в елеватор",
        "ArtistName":"Anna Ivanenko",
        "ArtistLink":"https://www.instagram.com/anaivan/",
        "ImageType":"32.jpg"
      },
      {
        "Tokenid":"33",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"16:58",
        "TwitterUrl":"https://twitter.com/voxukraine/status/1497224494527787010",
        "TwitterUsername":"voxukraine",
        "Headline":"The russian military used “Uragan” to fire on shelter and kindergarten. There are wounded and killed, including children",
        "DescriptionEnglish":"The VoxUkraine had verified the usage of Uragan rocket launcher by russian military, it has destroyed kindergarten and killed children there.",
        "DescriptionUkrainian":"Російські військові використовували «Ураган» для обстрілу укриття та дитячого садка. Є поранені та вбиті, в тому числі діти",
        "ArtistName":"Olena Dziura",
        "ArtistLink":"https://www.instagram.com/olenadzen/",
        "ImageType":"33.jpg"
      },
      {
        "Tokenid":"34",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"17:30",
        "TwitterUrl":"https://twitter.com/Kabmin_UA_e/status/1497232442339508228",
        "TwitterUsername":"Kabmin_UA_e",
        "Headline":"Almost UAH 300 million transferred to #NBU’s special account for Ukraine’s Armed Forces over past 24 hours\n\n#Ukraine #Emergency #Defense #StopRussianAggression",
        "DescriptionEnglish":"The special donation account of Natonial Bank of Ukraine has received more than 300 millions UAH for the past 24 hours",
        "DescriptionUkrainian":"За минулу добу на спецрахунок #НБУ для Збройних сил України перераховано майже 300 млн грн.",
        "ArtistName":"Varvara Perekrest",
        "ArtistLink":"varvaraperekrest.com",
        "ImageType":"34.jpg"
      },
      {
        "Tokenid":"35",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"18:42",
        "TwitterUrl":"https://twitter.com/RFERL/status/1497250646218747907",
        "TwitterUsername":"RFERL",
        "Headline":"Residents of Kyiv witnessed large explosions above their city in the early hours of February 25. Several amateur videos showed the skies light up as loud explosions shook the capital. ",
        "DescriptionEnglish":"On the videos done by Kyiv residents were captured huge and loud explosions",
        "DescriptionUkrainian":"Кияни вранці 25 лютого стали свідками великих вибухів над своїм містом.",
        "ArtistName":"Ivan Ponomarchuk",
        "ArtistLink":"https://www.behance.net/cordduro",
        "ImageType":"35.jpg"
      },
      {
        "Tokenid":"36",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"20:44",
        "TwitterUrl":"https://twitter.com/Vitaliy_Klychko/status/1497281386440441860",
        "TwitterUsername":"Vitaliy_Klychko",
        "Headline":"5 explosions occurred with an interval of 3-5 minutes near CHP-6. Emergency services follow there. Let's find out the details.",
        "DescriptionEnglish":"Several explosions were reported aroud the combined heat and power plant-6",
        "DescriptionUkrainian":"5 вибухів сталися з інтервалом в 3-5 хвилин біля ТЕЦ-6. Аварійно-рятувальні служби слідують туди. З’ясовуємо деталі.",
        "ArtistName":"Darya Yehorova",
        "ArtistLink":"https://www.behance.net/daryelazy",
        "ImageType":"36.jpg"
      },
      {
        "Tokenid":"37",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"21:06",
        "TwitterUrl":"https://twitter.com/MVS_UA/status/1497286812976386048",
        "TwitterUsername":"MVS_UA",
        "Headline":"Kyiv city authorities are appealing to residents of high-rise buildings - urgently check the roofs for signs.\n\n If signs are found, cover them with earth or cover them with something! This is probably the route for aviation to objects where they can strike.",
        "DescriptionEnglish":"Authorities are warning about the special signs on the roofs of high builidings. Signs may be the marks for the rocket attacks.",
        "DescriptionUkrainian":"Міська влада Києва звертається до мешканців багатоповерхових будинків - терміново перевірте дахи на наявність міток.\n\nУ разі виявлення позначок-засипте їх землею або чимось накрийте!Так вірогідно помічений маршрут для авіації до об'єктів, де можуть наносити удари.",
        "ArtistName":"Iryna Vale",
        "ArtistLink":"https://www.instagram.com/vale.illustration/ ",
        "ImageType":"37.jpg"
      },
      {
        "Tokenid":"38",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"21:19",
        "TwitterUrl":"https://twitter.com/BBCWorld/status/1497290167262011392",
        "TwitterUsername":"BBCWorld",
        "Headline":"Radiation spike at Chernobyl nuclear plant seized by Russian forces",
        "DescriptionEnglish":"Monitoring data shows that A radiation spike has been recorded near Chernobyl's nuclear power plant which has been seized by Russian forces. The rise was caused by heavy military vehicles stirring contaminated soil in the 4,000-sq-km (2,485 sq-mile) exclusion zone surrounding the abandoned plant",
        "DescriptionUkrainian":"Сплеск радіації на Чорнобильській АЕС, яку захопили російські війська",
        "ArtistName":"Hordiy Vasylash",
        "ArtistLink":"https://hordiyvasylash.com/ ",
        "ImageType":"38.jpg"
      },
      {
        "Tokenid":"39",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"21:44",
        "TwitterUrl":"https://twitter.com/RFERL/status/1497296537424121862",
        "TwitterUsername":"RFERL",
        "Headline":"RFE/RL correspondent Maryan Kushnir came across destroyed Russian military equipment, including Grad missile launchers, outside Kharkiv, Ukraine's second-largest city on February 25. He also found an unexploded missile that hit a residential area of the city.",
        "DescriptionEnglish":"The correspondent has captured the results of russian military atack in the area of Kharkiv city. He had found an unexploded missile right in the residential area of Kharkiv.",
        "DescriptionUkrainian":"Під Харковом кореспондент натрапив на знищену російську військову техніку, в тому числі пускові установки «Град», Знайшов нерозірвану ракету, яка влучила в житловий район міста.",
        "ArtistName":"Julie Grechukh",
        "ArtistLink":"https://www.behance.net/juliegrechb30e",
        "ImageType":"39.jpg"
      },
      {
        "Tokenid":"40",
        "DayNo":"2",
        "FullDate":"2/25/2022",
        "Time":"22:31",
        "TwitterUrl":"https://twitter.com/ng_ukraine/status/1497308222709026817",
        "TwitterUsername":"ng_ukraine",
        "Headline":"The fake territorial defense unit was exposed.\nBe careful, hostile sabotage and reconnaissance groups are operating in the city.",
        "DescriptionEnglish":"The hostile sabotage and reconnaissance groups are operating in the city. They imitate being ukrainian territorial defence, one such group was exposed.",
        "DescriptionUkrainian":"Було викрито фейковий підрозділ територіальної оборони",
        "ArtistName":"Daria Lapchynska ",
        "ArtistLink":"http://lapchynska.tilda.ws",
        "ImageType":"40.jpg"
      }
    ]
  },
  {
    "dayNo":3,
    "date":"26 Feb 2022",
    "events":[
      {
        "Tokenid":"41",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"00:17",
        "TwitterUrl":"https://twitter.com/ua_parliament/status/1497335041399136266?s=20&t=Eo11jrC1DqkrhDjs3z1qEw",
        "TwitterUsername":"ua_parliament",
        "Headline":"Speaker @r_stefanchuk held a phone call with the President of the Bundestag @baerbelbas . After she was appointed for the position, she assured that she would protect democracy from enemies. Today, the entire Ukrainian people are also defending democracy from the enemy.",
        "DescriptionEnglish":"Speaker @r_stefanchuk held a phone call with the President of the Bundestag assuring her position to protect democracy and stand for Ukraine",
        "DescriptionUkrainian":"Спікер @r_stefanchuk провів телефонну розмову з Президентом",
        "ArtistName":"Alina Litv",
        "ArtistLink":"",
        "ImageType":"41.jpg"
      },
      {
        "Tokenid":"42",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"00:39",
        "TwitterUrl":"https://twitter.com/ua_parliament/status/1497340592975659011",
        "TwitterUsername":"ua_parliament",
        "Headline":"Two hours ago, a woman gave birth in the #Kyiv subway. This news is what gives us hope!",
        "DescriptionEnglish":"The woman that was hidding in the bomb shelter in the subway, gave birth to her child right there!",
        "DescriptionUkrainian":"Дві години тому в #Київському метро народила жінка. Ця новина дає нам надію!",
        "ArtistName":"Katerina Kolesnik",
        "ArtistLink":"https://instagram.com/ode_to_shade",
        "ImageType":"42.jpg"
      },
      {
        "Tokenid":"43",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"00:55",
        "TwitterUrl":"https://twitter.com/GeneralStaffUA/status/1497344479094792195?s=20&t=DIXRtv9VrLakvDGLPQ55Yg",
        "TwitterUsername":"GeneralStaffUA",
        "Headline":"Ukraine Anti Air Forces shut down russian paratrooper airplane near Vasilkiv",
        "DescriptionEnglish":"Commander in chief of Ukrainian Armed Forces has reported about positive results of Ukrainian air defence systems. Russian paratrooper airplane was shut down near Vasilkiv",
        "DescriptionUkrainian":"Протиповітряні сили України закрили російський десантний літак поблизу Василькова",
        "ArtistName":"Tina Tykhonenko",
        "ArtistLink":"https://instagram.com/tihotak?utm_medium=copy_link",
        "ImageType":"43.jpg"
      },
      {
        "Tokenid":"44",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"09:11",
        "TwitterUrl":"https://twitter.com/ua_parliament/status/1497469335262142469?s=20&t=Eo11jrC1DqkrhDjs3z1qEw",
        "TwitterUsername":"ua_parliament",
        "Headline":"Results of the russian aggression in #Kyiv",
        "DescriptionEnglish":"Residential buildings in Kyiv are destroyed by the rocket attacks of russian army",
        "DescriptionUkrainian":"Наслідки російської агресії в #Києві!",
        "ArtistName":"Ann Khomych",
        "ArtistLink":"https://www.behance.net/aniakhomych",
        "ImageType":"44.jpg"
      },
      {
        "Tokenid":"45",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"09:14",
        "TwitterUrl":"https://twitter.com/DefenceU/status/1497470212496666626?s=20&t=DIXRtv9VrLakvDGLPQ55Yg",
        "TwitterUsername":"DefenceU",
        "Headline":"#Operative_information from the SES of Ukraine\n\n \"We are recording another war crime against the civilian population of Ukraine. Rescuers are evacuating residents of a high-rise building at 6A Lobonovsky Avenue, where a shell hit a residential building on the 17th and 18th floors on February 26.\"",
        "DescriptionEnglish":"The records of ukrainian rescuers evacuating civil people after the missile hit of the high-rise building in Kyiv",
        "DescriptionUkrainian":"Фіксуємо черговий воєнний злочин проти мирного населення України.Рятувальники проводять евакуацію мешканців багатоповерхівки по проспекту Лобоновського 6А, де 26.02 сталося попадання снаряду в житловий будинок на рівні 17 та 18 поверхів",
        "ArtistName":"Erlikh Dima",
        "ArtistLink":"https://erlikh-com.webflow.io/",
        "ImageType":"45.jpg"
      },
      {
        "Tokenid":"46",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"10:58",
        "TwitterUrl":"https://twitter.com/DmytroKuleba/status/1497496218359898116?s=20&t=Eo11jrC1DqkrhDjs3z1qEw",
        "TwitterUsername":"DmytroKuleba",
        "Headline":"We did it. Cyprus confirmed it will not block the decision to ban Russia from SWIFT. Ukrainian diplomacy keeps working 24/7 to achieve important decisions and protect Ukraine from Russian invaders.",
        "DescriptionEnglish":"Cyprus confirmed it will not block the decision to ban Russia from SWIFT.",
        "DescriptionUkrainian":"Кіпр підтвердив, що не блокуватиме рішення заборонити Росії SWIFT.",
        "ArtistName":"Stasya Samar (Anastasiya Samarkina)",
        "ArtistLink":"https://www.behance.net/stassamar ",
        "ImageType":"46.jpg"
      },
      {
        "Tokenid":"47",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"11:52",
        "TwitterUrl":"https://twitter.com/ng_ukraine/status/1497509840121389060?s=20&t=MIslYn49SqTKiyrRyrZ9EA",
        "TwitterUsername":"ng_ukraine",
        "Headline":"Ukraine appeals to the International Committee of the Red Cross to help to withdraw thousands of bodies of Russian soldiers from our country to Russia!",
        "DescriptionEnglish":"Thousands of bodies of Russian soldiers need to withdrawn from Ukraine, it is an appeal of Ukraine to the International Committee",
        "DescriptionUkrainian":"Україна звертається до Міжнародного комітету Червоного Хреста з проханням допомогти вивести тисячі тіл російських солдатів з нашої країни до Росії!",
        "ArtistName":"Mitya Fenechkin",
        "ArtistLink":"https://instagram.com/mityafenechkin",
        "ImageType":"47.jpg"
      },
      {
        "Tokenid":"48",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"12:33",
        "TwitterUrl":"https://twitter.com/ua_parliament/status/1497520231643848707?s=20&t=Eo11jrC1DqkrhDjs3z1qEw",
        "TwitterUsername":"ua_parliament",
        "Headline":"#Hungary is among the countries advocating against banning russia from the #SWIFT IPS. Previously, Hungary had banned Ukraine from joining the  @NATO\n cybercenter. We call on Viktor #Orbán to support Ukraine's choice for Euro-Atlantic integration and our inalienable right for self-determination.",
        "DescriptionEnglish":"Ukraine calls on Viktor Orban to support Ukraine and not to advocate against banning Russia from SWIFT",
        "DescriptionUkrainian":"Угорщина входить до числа країн, які виступають проти заборони SWIFT в Росії",
        "ArtistName":"yanka.ki  ",
        "ArtistLink":"https://www.instagram.com/yanka.ki/",
        "ImageType":"48.jpg"
      },
      {
        "Tokenid":"49",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"12:49",
        "TwitterUrl":"https://twitter.com/MFA_Ukraine/status/1497524244657356807?s=20&t=DIXRtv9VrLakvDGLPQ55Yg",
        "TwitterUsername":"MFA_Ukraine",
        "Headline":"Ordinary Russian citizens have not yet realized that Russia’s attack on Ukraine will affect them personally. Sanctions do not only apply to oligarchs. Each and every Russian will feel them. Hyperinflation, deficits, queues, devaluation of savings, unemployment. Russians, wake up!",
        "DescriptionEnglish":"Ministry of Foreign Affairs of Ukraine warns ordinary Russian citizens about the potential risks of deficits, hyperinflation, devaluation of savings and umployment in Russia.",
        "DescriptionUkrainian":"Прості громадяни Росії ще не усвідомили, що напад Росії на Україну торкнеться їх особисто.",
        "ArtistName":"Yaroslava Shkolna",
        "ArtistLink":"https://www.instagram.com/yrs_evo/",
        "ImageType":"49.jpg"
      },
      {
        "Tokenid":"50",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"14:06",
        "TwitterUrl":"https://twitter.com/ua_parliament/status/1497543591736094723?s=20&t=Eo11jrC1DqkrhDjs3z1qEw",
        "TwitterUsername":"ua_parliament",
        "Headline":"\n“I was just speaking to Orsolya Kovács, the Hungarian ambassador to Poland\n\nHungary is not going block any of the sanctions against the Russian Federation, including the SWIFT ban.”\n\nWe’d like to thank everyone for their help! We’re one step closer to our victory!",
        "DescriptionEnglish":"Conversation with Orsolya Kovács, the Hungarian ambassador shows that Hungary is not going block any of the sanctions against the Russian Federation, including the SWIFT ban.",
        "DescriptionUkrainian":"Розмова з послом Угорщини Орсолею Ковач показує, що Угорщина не збирається блокувати жодних санкцій проти Російської Федерації, включаючи заборону SWIFT.",
        "ArtistName":"Bogdan ",
        "ArtistLink":"https://dribbble.com/gbogdan",
        "ImageType":"50.gif"
      },
      {
        "Tokenid":"51",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"14:09",
        "TwitterUrl":"https://twitter.com/NATOBrazeB/status/1497544314339172356?s=20&t=DiIpYAbwP7o7Ob_NjEA38g",
        "TwitterUsername":"NATOBrazeB",
        "Headline":"Poland’s Defence minister announces that a convoy delivered supply of ammunition to Ukraine.\n\n#NATO Allies announced delivery of military supplies and aid (Slovakia, Canada, USA, Estonia, Latvia, Lithuania, others).\n\n#StrongerTogether #StandWithUkraine",
        "DescriptionEnglish":"The supply of ammunition to help Ukraine supported by Poland is delivered",
        "DescriptionUkrainian":"Міністр оборони Польщі повідомив, що колона доставила в Україну боєприпаси.",
        "ArtistName":"Katerina Kolesnik",
        "ArtistLink":"https://instagram.com/ode_to_shade",
        "ImageType":"51.jpg"
      },
      {
        "Tokenid":"52",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"16:05",
        "TwitterUrl":"https://twitter.com/GeneralStaffUA/status/1497573479390064640?s=20&t=DIXRtv9VrLakvDGLPQ55Yg",
        "TwitterUsername":"GeneralStaffUA",
        "Headline":"In the waters of the Black Sea, the ship of the Russian Black Sea Fleet \"friendly fire\" destroyed its military aircraft.",
        "DescriptionEnglish":"Naval forces of Ukraine reported that Russian Fleet in  Black Sea had destroyed its own military aircraft",
        "DescriptionUkrainian":"В акваторії Чорного моря корабель ЧФ РФ \"дружнім вогнем\" знищив свій військовий літак.",
        "ArtistName":"Margarita Polovinko ",
        "ArtistLink":"https://www.behance.net/polovinkomarharyta",
        "ImageType":"52.jpg"
      },
      {
        "Tokenid":"53",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"16:40",
        "TwitterUrl":"https://twitter.com/NATO/status/1497582295913570308?s=20&t=DiIpYAbwP7o7Ob_NjEA38g",
        "TwitterUsername":"NATO",
        "Headline":"We call on Russia to stop this senseless war. #StandWithUkraine",
        "DescriptionEnglish":"NATO calls on Russia to stop war. \"Kremlin's war on Ukraine will not make Russia more secure\" said Secretary General Jens Stoltenberg",
        "DescriptionUkrainian":"НАТО закликає Росію припинити цю безглузду війну.",
        "ArtistName":"Alina Kropachova",
        "ArtistLink":"https://www.behance.net/AlinaKro\n",
        "ImageType":"53.jpg"
      },
      {
        "Tokenid":"54",
        "DayNo":"3",
        "FullDate":"2/26/2022",
        "Time":"17:41",
        "TwitterUrl":"https://twitter.com/ua_parliament/status/1497597577151266817?s=20&t=Eo11jrC1DqkrhDjs3z1qEw",
        "TwitterUsername":"ua_parliament",
        "Headline":"21st century. One of the districts of #Kyiv. Those who shout about \"Nazism in #Ukraine\" act like actual Nazis. As a result of enemy shelling, the missiles hit the capital's skyscraper and hangar. Two Kyiv residents were killed, and six were seriously injured.",
        "DescriptionEnglish":"As a result of russian shelling, the hangar and skyscraper in Kyiv was destroyed, two residents were killed, several wounded.",
        "DescriptionUkrainian":"Ті, хто кричить про нацизм в #Україна\", діють як справжні нацисти..., ракети влучили в столичний хмарочос і ангар...\"",
        "ArtistName":"Vlad Kononok",
        "ArtistLink":"https://instagram.com/vladkononok",
        "ImageType":"54.png"
      }
    ]
  }
];

export default WarlineData;
