export const ITEMS = [
  {
    museum: 'National Art Museum of Ukraine',
    name: 'Still life. Bottles.',
    author: 'Oleksander Bohomazov, 1915',
    url: '/roosters/NAMU',
    link: 'https://namumuseum.business.site/',
  },
  {
    museum: 'Latvian National Museum of Art',
    name: 'Photons landscape. # 32',
    author: 'Gints Gabrāns, 2010',
    url: '/roosters/LNMM PL-32',
    link: 'https://www.gabrans.com/photonpainting.php',
  },
  {
    museum: 'Latvian National Museum of Art',
    name: 'Photon landscape. # 4',
    author: 'Gints Gabrāns, 2010',
    url: '/roosters/LNMM PL-4',
    link: 'https://www.gabrans.com/photonpainting.php',
  },
  {
    museum: 'Centre Pompidou',
    name: 'IKB 3, Monochrome bleu',
    author: 'Yves Klein, 1960',
    url: '/roosters/Centre Pompidou',
  },
  {
    museum: 'Museo del Prado',
    name: 'The Garden of Earthly Delights Triptych',
    author: 'Hieronymus Bosch, 1490–1500',
    url: '/roosters/Prado Museum',
  },
  {
    museum: 'Guggenheim Museum',
    name: 'Composition 8',
    author: 'Vasily Kandinsky, 1923',
    url: '/roosters/Guggenheim Museum NY',
  },
  {
    museum: 'MoMA',
    name: 'Number 1A',
    author: 'Jackson Pollock, 1948',
    url: '/roosters/MoMa',
  },
  {
    museum: 'New Museum of Contemporary Art',
    name: 'Jungle of Desire',
    author: 'Wong Ping, 2015',
    url: '/roosters/New Museum of Contemporary Art',
  },
  {
    museum: 'Museum of Contemporary Art Chicago',
    name: 'Jellyfish Eyes',
    author: 'Takashi Murakami, 2002',
    url: '/roosters/The Museum of Contemporary Art (MCA) Chicago',
  },
  {
    museum: 'Whitney Museum',
    name: 'Monday, May 1, 1989',
    author: 'Alexandra Bell, 2018–2019',
    url: '/roosters/Whitney Museum',
  },
  {
    museum: "MACBA Museu d'Art Contemporani de Barcelona",
    name: 'Self-Portrait',
    author: 'Jean-Michel Basquiat, 1986',
    url: '/roosters/Museu d’Art Contemporani de Barcelona',
  },
  {
    museum: 'Museu Coleção Berardo',
    name: 'Mirror',
    author: 'Roy Lichtenstein, 1971',
    url: '/roosters/Berardo museum Lisboa',
  },
  {
    museum: 'KUMU',
    name: 'Huuled',
    author: 'Ülo Sooster, 1964',
    url: '/roosters/Museum KUMU',
  },
];
