export const ITEMS = [
  {
    id: 1,
    museum: 'Centre Pompidou',
    name: 'IKB 3, Monochrome bleu',
    author: 'Yves Klein, 1960',
    url: '/1.mview',
  },
  {
    id: 2,
    museum: 'Museo del Prado',
    name: 'The Garden of Earthly Delights Triptych',
    author: 'Hieronymus Bosch, 1490–1500',
    url: '/2.mview',
  },
  {
    id: 3,
    museum: 'Guggenheim Museum',
    name: 'Composition 8',
    author: 'Vasily Kandinsky, 1923',
    url: '/1.mview',
  },
  {
    id: 4,
    museum: 'MoMA',
    name: 'Number 1A',
    author: 'Jackson Pollock, 1948',
    url: '/1.mview',
  },
  {
    id: 5,
    museum: 'New Museum of Contemporary Art',
    name: 'Jungle of Desire',
    author: 'Wong Ping, 2015',
    url: '/1.mview',
  },
  {
    id: 6,
    museum: 'Museum of Contemporary Art Chicago',
    name: 'Jellyfish Eyes',
    author: 'Takashi Murakami, 2002',
    url: '/1.mview',
  },
  {
    id: 7,
    museum: 'Whitney Museum',
    name: 'Monday, May 1, 1989',
    author: 'Alexandra Bell, 2018–2019',
    url: '/1.mview',
  },
  {
    id: 8,
    museum: "MACBA Museu d'Art Contemporani de Barcelona",
    name: 'Self-Portrait',
    author: 'Jean-Michel Basquiat, 1986',
    url: '/1.mview',
  },
  {
    id: 9,
    museum: 'National Art Museum of Ukraine',
    name: 'Still life. Bottles.',
    author: 'Oleksander Bohomazov, 1915',
    url: '/1.mview',
  },
  {
    id: 10,
    museum: 'Museu Coleção Berardo',
    name: 'Mirror',
    author: 'Roy Lichtenstein, 1971',
    url: '/1.mview',
  },
  {
    id: 11,
    museum: 'KUMU',
    name: 'Huuled',
    author: 'Ülo Sooster, 1964',
    url: '/1.mview',
  },
];
